<?php
/**
* Create administration form for variables
* @return form content for section
*/
/*
    KickApps Single Sign-On Drupal Plugin
    Copyright (C) 2007  KickApps Inc.

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/***
* Register the administration screen with Drupal
* @return the form info
*/
function kickapps_menu() {
	watchdog("KickApps", "Make menu");

	$items = array();

	$items['community'] = array(
		'title' => 'My Community',
		'page callback' => 'kickapps_home',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

        $items['community/%'] = array(
		'title' => 'My Community',
		'page callback' => 'kickapps_community',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['community/volunteerteams'] = array(
		'title' => 'Volunteer Teams',
		'page callback' => 'kickapps_volunteerteams',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['community/offlinevolunteerunit'] = array(
		'title' => 'Offline Volunteer Unit',
		'page callback' => 'kickapps_offlinevolunteerunit',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['community/volunteerteamdashboard'] = array(
		'title' => 'Offline Volunteer Unit',
		'page callback' => 'kickapps_volunteerteamdashboard',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['community/assignteam'] = array(
		'title' => 'My Community',
		'page callback' => 'kickapps_assignteam',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['community/members'] = array(
		'title' => 'My Community - Members',
		'page callback' => 'kickapps_members',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/settings/kickapps'] = array(
		'title' => 'KickApps Single Sign-On Module Settings',
		'description' => 'Configure the connection information for your KickApps Affiliate Site',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('kickapps_admin'),
		'access callback' => 'user_access',
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['community/loadteamtable'] = array(
		'title' => 'My Community',
		'page callback' => 'kickapps_loadteamtable',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/manage'] = array(
		'title' => 'Manage Kickapps Group',
		'page callback' => 'kickapps_manage_group',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/content'] = array(
		'title' => '',
		'page callback' => 'kickapps_manage_content',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/teamcontent'] = array(
		'title' => '',
		'page callback' => 'kickapps_manage_teamcontent',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/updatetitle'] = array(
		'title' => '',
		'page callback' => 'kickapps_update_title',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/addcategory'] = array(
		'title' => '',
		'page callback' => 'kickapps_add_category',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/addcategoryteams'] = array(
		'title' => '',
		'page callback' => 'kickapps_add_category_teams',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/deletecategory'] = array(
		'title' => '',
		'page callback' => 'kickapps_delete_category',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/editteam'] = array(
		'title' => '',
		'page callback' => 'kickapps_update_team',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/disableMember'] = array(
		'title' => '',
		'page callback' => 'kickapps_disable_member',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/addmultiplemember'] = array(
		'title' => '',
		'page callback' => 'kickapps_addmultiplemember_member',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['community/manageteam'] = array(
		'title' => '',
		'page callback' => 'kickapps_manage_team',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['community/loadtroopteams'] = array(
		'title' => '',
		'page callback' => 'kickapps_troop_teams',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/postannounce'] = array(
		'title' => '',
		'page callback' => 'kickapps_post_retreive_announce',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/kickapps/removeannounce'] = array(
		'title' => '',
		'page callback' => 'kickapps_remove_retreive_announce',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	$items['admin/settings/kickapps-maintenance'] = array(
		'title' => '',
		'page callback' => 'kickapps_maintenance',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	return $items;
}

function kickapps_getStatus(){
	// $xml = simplexml_load_file("/vol/var/www/drupal/sites/all/modules/kickapps/kickapps_maintain.xml")
	//        or die("Error: Cannot create object");

	// return $xml->children()->kickapps->get->kmaintain_value;
	return true;
}

function kickapps_maintenance(){

 $sHtml = '';

 if(isset($_POST['status'])){
	/*$sqlUpdate = "UPDATE kickapps_maintenance
					SET kmaintain_value = %d
					WHERE kmaintain_id = %d";

	db_query($sqlUpdate, array($_POST['status'], 1));*/

	$file = "/vol/var/www/drupal/sites/all/modules/kickapps/kickapps_maintain.xml";
	$fp = fopen($file, "rb") or die("cannot open file");
	$str = fread($fp, filesize($file));
	$xml = new DOMDocument();
	$xml->formatOutput = true;
	$xml->preserveWhiteSpace = false;
	$xml->loadXML($str) or die("Error");
	$root   = $xml->documentElement;
	$fnode  = $root->firstChild;
	$ori    = $fnode->childNodes->item(0);
	$fnode->removeChild($ori);

	$ori = $fnode->childNodes->item(0);
	$id = $xml->createElement("id");
	$idText = $xml->createTextNode("0");
	$id->appendChild($idText);
	$title     = $xml->createElement("kmaintain_title");
	$titleText = $xml->createTextNode("Activate Kickapps");
	$title->appendChild($titleText);
	$kval     = $xml->createElement("kmaintain_value");
	$kvalText = $xml->createTextNode("{$_POST['status']}");
	$kval->appendChild($kvalText);
	$k   = $xml->createElement("get");
	$k->appendChild($id);
	$k->appendChild($title);
	$k->appendChild($kval);
	$fnode->insertBefore($k,$ori);
	$xml->save('/vol/var/www/drupal/sites/all/modules/kickapps/kickapps_maintain.xml');

	$sHtml = 'Your Configuration was successfully changed.<br/>';
 }

 $sHtml .= '<div style="padding-bottom:12px;">
	        <br/><h3>Kickapps Maintenance</h3><br/>
			<b>Kickapps Status:</b>
	 	   </div>';

 $kid = kickapps_getStatus();

 $sHtml .= '<form method="post" action="/admin/settings/kickapps-maintenance">';

 if($kid == 1){
 $sHtml .= '<input type="radio" id="status" name="status" value="1" checked /> Enable &nbsp;&nbsp;';
 $sHtml .= '&nbsp;&nbsp;<input type="radio" id="status" name="status" value="0" /> Disable';
 } else{
 $sHtml .= '<input type="radio" id="status" name="status" value="1" /> Enable &nbsp;&nbsp;';
 $sHtml .= '&nbsp;&nbsp;<input type="radio" id="status" name="status" value="0" checked/> Disable';
 }

 $sHtml .= '<br/><br/><input type="submit" id="statussubmit" name="statussubmit" value="Save configuration" />
		   </form>';
 $sHtml .= '<br/>
		 When set to "Enable", all members will be able to browse kickapps normally. When set to "Disable",
		 kickapps will not be available to all members.
		 ';
 return $sHtml;
}

function kickapps_remove_retreive_announce($teamannounceremoveid, $teamid){

	$sqlDelete = "DELETE FROM {hope_team_news} WHERE {teamnews_id} = %d";
	db_query($sqlDelete, $teamannounceremoveid);

	$sOutput = kickapps_retreive_announce($teamid);

	echo json_encode(array("OUTPUT" => $sOutput));
}

function kickapps_post_retreive_announce($teamid, $announcetxt){

	$date = strtotime(date("F j, Y, g:i a"));

	$sqlInsert = "INSERT INTO {hope_team_news} VALUES(NULL, '{$teamid}', '{$announcetxt}', '{$date}')";
	db_query($sqlInsert);

	$sOutput = kickapps_retreive_announce($teamid);

	echo json_encode(array("OUTPUT" => $sOutput));
}

function kickapps_retreive_announce($teamid){

	$sqlAnnounce = "SELECT teamnews_id, team_id, announce_text, announce_date
				FROM hope_team_news
				WHERE team_id = %d
				ORDER BY teamnews_id DESC";
	$oAnnounceResult = db_query($sqlAnnounce, $teamid);

	$sOutput = '';
	while ($oAnnounce = db_fetch_object($oAnnounceResult)){
		$sOutput .= $oAnnounce->announce_text.' <span style="font-size:10px;"><b>'.date("F j, Y, g:i a", $oAnnounce->announce_date).' <a href="javascript:void(0);" onclick="team_announcement_remove(\''.$oAnnounce->teamnews_id.'\',\''.$teamid.'\');">[remove]</a></b></span>'.'<br/><br/>';
	}

	return $sOutput;
}

function kickapps_troop_teams($id, $type, $coltroop, $kind){
   global $user;

   $kickappsteam_id = db_result(db_query("SELECT A.team_id
					FROM hope_teamusers A
					WHERE A.uid = '{$user->uid}'"));

	switch($type){
	case 'troop':
	$troopid = $id;
	break;
	case 'team':
	$iTroopResult = db_query("SELECT A.troop_id, B.wing_id
					FROM drupal.hope_team A
					LEFT JOIN drupal.hope_troop B ON B.troop_id = A.troop_id
					WHERE A.kickappsteam_id = '{$id}'");

	$iTroop = db_fetch_object($iTroopResult);
	mysqli_free_result($iTroopResult);
	$troopid = $iTroop->troop_id;
	$wing_id = $iTroop->wing_id;

	$sqlTroop = "SELECT A.troop_id
				FROM hope_troop A
				WHERE A.wing_id = %d";
	$oTroopResult = db_query($sqlTroop, $wing_id);
	$coltroop1 = 0;
	$coltroop = '';
	while ($oTroop = db_fetch_object($oTroopResult)){
		if($oTroop->troop_id == $troopid){
		$coltroop = $coltroop1 + 1;
		}
	$coltroop1++;
	}
	mysqli_free_result($oTroopResult);
	break;
	}

	//$theme_imgpath = 'http://www.hopecybary.org/themes/theme2010/images/';
	$theme_imgpath = $base_url.'/themes/theme2010/images/';

	$sOutput = '<div align="center" style="padding-left:130px;">';
	$sqlTeam = "SELECT A.kickappsteam_id, A.team_name, A.team_color, A.team_type, A.troop_id
					FROM hope_team A
					WHERE troop_id = %d";
	$oTeamResult = db_query($sqlTeam, $troopid);
	$colteam = 0;
	$lineteam = 0;
	while ($oTeam = db_fetch_object($oTeamResult)){
	$arr_teamname = explode(' ',$oTeam->team_name);
	$teamcolor = strtolower($arr_teamname[0]);
	$teamcolorfont = $teamcolor == 'blue' ? 'white': 'black';
		if($kind == 'volunteer'){
		//$linkPage = '/community/volunteerteamdashboard';
		$linkPage = $base_url.'/community/volunteerteamdashboard';	
		} else{
		//$linkPage = '/community/manageteam';
		$linkPage = $base_url.'/community/manageteam';
		}

		if($oTeam->kickappsteam_id == $kickappsteam_id){
			$sOutput .= '<div style="border:2px solid #1ef102;float:left;width:100px;height:60px;color:'.$teamcolorfont.';background-color:'.$teamcolor.';"><a href="'.$linkPage.'?teamid='.$oTeam->kickappsteam_id.'"><b style="color:'.$teamcolorfont.';">'.$oTeam->team_name.'</b></a><br/>'.calculateTeam('team',$oTeam->kickappsteam_id).' Member(s)</div><div style="float:left;width:10px;">&nbsp;</div>';
			$lineteam = $colteam;
		} else{
			$sOutput .= '<div style="border:1px solid #b3b3b3;float:left;width:100px;height:60px;color:'.$teamcolorfont.';background-color:'.$teamcolor.';"><a href="'.$linkPage.'?teamid='.$oTeam->kickappsteam_id.'"><b style="color:'.$teamcolorfont.';">'.$oTeam->team_name.'</b></a><br/>'.calculateTeam('team',$oTeam->kickappsteam_id).' Member(s)</div><div style="float:left;width:10px;">&nbsp;</div>';
		}
	$colteam++;
	}
	mysqli_free_result($oTeamResult);
	$sOutput .= '</div>';

	if($lineteam !== 0){
		$sOutput .= '<div align="center" style="padding-left:130px;clear:both;">';
		$colyourteam = 0;
		while($colyourteam <= 4){
			if($colyourteam == $lineteam){
				$sOutput .= '<div style="float:left;width:100px;height:60px;">
								<img src="'.$theme_imgpath.'balloon_thisisyourteam.gif" />
							</div>
							<div style="float:left;width:10px;">
								&nbsp;
							</div>';
			} else{
				$sOutput .= '<div style="float:left;width:100px;height:60px;">
								&nbsp;
							</div>
							<div style="float:left;width:10px;">
								&nbsp;
							</div>';
			}
		$colyourteam++;
		}
		$sOutput .= '</div>';
	}

	$sLines = '<div style="clear:both;" id="teams_lines">
					<div><img src="'.$theme_imgpath.'z_level3line'.$coltroop.'.gif" /></div>
					<div><img src="'.$theme_imgpath.'z_level3line.png" /></div>
				</div>';

	echo json_encode(array("OUTPUT" => $sOutput, "LINES" => $sLines));
}

function kickapps_addmultiplemember_member($ids, $teamid){

	$arr_ids = explode('_', $ids);

	foreach($arr_ids as $id){
	$sqlInsert = "INSERT INTO {hope_teamusers} VALUES(NULL, '{$teamid}', '{$id}', NULL, NULL)";
	db_query($sqlInsert);
	}

	$memberList = '<select id="teams_available_hopeful" name="teams_available_hopeful[]" size="10" style="width:275px; margin-top:5px;" multiple="multiple">'.kickapps_fill_dropdown_teamhopeful($teamid).'</select>';

	$sOutput = kickapps_MembersRes($teamid);
	echo json_encode(array("STATUS" => 'Success', "RES" => $sOutput, "OPTION" => $memberList));
}

function kickapps_disable_member($id, $kickappsteam_id){
/*
	$sqlUpdate = "UPDATE hope_teamusers
					SET status = '%s'
					WHERE team_userid = %d";

	db_query($sqlUpdate, array(1, $id));*/

	$sqlDelete = "DELETE FROM {hope_teamusers} WHERE {team_userid} = %d";
	db_query($sqlDelete, $id);

	$sOutput = kickapps_MembersRes($kickappsteam_id);
	$memberList = '<select id="teams_available_hopeful" name="teams_available_hopeful[]" size="10" style="width:275px; margin-top:5px;" multiple="multiple">'.kickapps_fill_dropdown_teamhopeful($kickappsteam_id).'</select>';

	echo json_encode(array("STATUS" => 'Success', "RES" => $sOutput, "OPTION" => $memberList));
}

function kickapps_update_team($id, $teamname, $teamkid, $teamcolor){

	$table = 'hope_team';

	$sqlUpdate = "UPDATE {$table}
					SET team_name = '%s',
						kickappsteam_id = '%d',
						team_color = '%s'
					WHERE team_id = %d";

	db_query($sqlUpdate, array($teamname, $teamkid, $teamcolor, $id));
	echo json_encode(array("STATUS" => 'Success'));
}

function kickapps_delete_category($type, $id){
	switch($type){
	case 'div':
		$fieldname = 'div_name';
		$fieldid = 'div_id';
		$table = 'hope_division';
	break;
	case 'group':
		$fieldname = 'group_name';
		$fieldid = 'group_id';
		$table = 'hope_group';
		$parentdfield = 'div_id';
	break;
	case 'wing':
		$fieldname = 'wing_name';
		$fieldid = 'wing_id';
		$table = 'hope_wing';
		$parentdfield = 'group_id';
	break;
	case 'troop':
		$fieldname = 'troop_name';
		$fieldid = 'troop_id';
		$table = 'hope_troop';
		$parentdfield = 'wing_id';
	break;
	case 'team':
		$fieldname = 'team_name';
		$fieldid = 'team_id';
		$table = 'hope_team';
		$parentdfield = 'troop_id';
	break;
	}

	$sqlDelete = "DELETE FROM {$table} WHERE {$fieldid} = %d";

	db_query($sqlDelete, array($id));

	echo json_encode(array("STATUS" => 'Success'));
}

function kickapps_add_category_teams($type, $teamtitleName, $teamKID, $teamColor, $parent_id){

	$fieldname = 'team_name';
	$fieldid = 'team_id';
	$table = 'hope_team';
	$parentfield = 'troop_id';

	$sqlInsert = "INSERT INTO {$table} VALUES(NULL, '{$parent_id}', '{$teamKID}', '{$teamtitleName}', '{$teamColor}', 'red')";
	db_query($sqlInsert);
	$sOutput = kickapps_ChildRes($fieldid, $fieldname, $table, $parentfield, $parent_id, $type);

	echo json_encode(array("STATUS" => 'Success', "RES" => $sOutput));
}

function kickapps_add_category($type, $newval, $parent_id){

	switch($type){
	case 'div':
		$fieldname = 'div_name';
		$fieldid = 'div_id';
		$table = 'hope_division';

		$sqlInsert = "INSERT INTO {$table} VALUES(NULL, '{$newval}')";
		db_query($sqlInsert);

	break;
	case 'group':
		$fieldname = 'group_name';
		$fieldid = 'group_id';
		$table = 'hope_group';
		$parentdid = 'div_id';
	break;
	case 'wing':
		$fieldname = 'wing_name';
		$fieldid = 'wing_id';
		$table = 'hope_wing';
		$parentdid = 'group_id';
	break;
	case 'troop':
		$fieldname = 'troop_name';
		$fieldid = 'troop_id';
		$table = 'hope_troop';
		$parentdid = 'wing_id';
	break;
	}

	$sOutput = '';
	if($type == 'group' || $type == 'wing' || $type == 'troop'){
	$sqlInsert = "INSERT INTO {$table} VALUES(NULL, '{$parent_id}', '{$newval}')";
	db_query($sqlInsert);
	$sOutput .= kickapps_ChildRes($fieldid, $fieldname, $table, $parentdid, $parent_id, $type);
	}

	echo json_encode(array("STATUS" => 'Success', "RES" => $sOutput));
}

function kickapps_ChildRes($fieldid, $fieldname, $table, $parentdid, $parent_id, $type){

$sQlchild = "SELECT {$fieldid}, {$fieldname}
							FROM {$table}
							WHERE {$parentdid} = %d";
		$ochildResult = db_query($sQlchild, array($parent_id));

		$sOutput = '';
				$bg_colors = array(0 => '#f0f0f0', 1 => '#d0d0d0');
				$c = 0;
				$ctr = 1;
				while($ochildRes = db_fetch_object($ochildResult)){

					$sOutput .= '<div style="width:100%;">
										<div style="float:left;height:30px;width:10%;background-color:'.$bg_colors[$c].'">&nbsp;&nbsp;<input type="radio" id="inputChild" name="inputChild" value="'.$ochildRes->$fieldid.'_'.$ochildRes->$fieldname.'"></div>
										<div style="float:left;height:30px;width:20%;background-color:'.$bg_colors[$c].'">'.$ochildRes->$fieldid.'</div>
										<div style="float:left;height:30px;width:70%;background-color:'.$bg_colors[$c].'"><span id="text_'.$ochildRes->$fieldid.'">'.$ochildRes->$fieldname.'</span>
												<div id="input_'.$ochildRes->$fieldid.'" style="display:none;">
													<input type="text" id="edittitleName_'.$ochildRes->$fieldid.'" name="edittitleName_'.$ochildRes->$fieldid.'" value=""/>
													<input type="hidden" id="edittitleID_'.$ochildRes->$fieldid.'" name="edittitleID_'.$ochildRes->$fieldid.'" value=""/>
													<input type="button" value="Update" onclick="UpdateTitleEach(\''.$ochildRes->$fieldid.'\',\''.$type.'\',\''.$parent_id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
												</div>
										</div>
								</div>';
					if($c == 0){
					$c = 1;
					}else{
					$c = 0;
					}
				$ctr++;
				}
				mysqli_free_result($ochildResult);
		$sOutput .= '';

return $sOutput;
}

function kickapps_update_title($type, $id, $newVal, $parent_id = ''){
	switch($type){
	case 'div':
		$fieldname = 'div_name';
		$fieldid = 'div_id';
		$table = 'hope_division';
	break;
	case 'group':
		$fieldname = 'group_name';
		$fieldid = 'group_id';
		$table = 'hope_group';
		$parentdfield = 'div_id';
	break;
	case 'wing':
		$fieldname = 'wing_name';
		$fieldid = 'wing_id';
		$table = 'hope_wing';
		$parentdfield = 'group_id';
	break;
	case 'troop':
		$fieldname = 'troop_name';
		$fieldid = 'troop_id';
		$table = 'hope_troop';
		$parentdfield = 'wing_id';
	break;
	case 'team':
		$fieldname = 'team_name';
		$fieldid = 'team_id';
		$table = 'hope_team';
		$parentdfield = 'troop_id';
	break;
	}

	$sqlUpdate = "UPDATE {$table}
						SET {$fieldname} = '{$newVal}'
						WHERE {$fieldid} = %d";

	db_query($sqlUpdate, array($id));

	$sOutput = '';
	if($type !== 'div'){
	$sOutput .= kickapps_ChildRes($fieldid, $fieldname, $table, $parentdfield, $parent_id, $type);
	}

	echo json_encode(array("STATUS" => 'Success', 'RES' => $sOutput));
}

function kickapps_manage_teamcontent($id){
	drupal_add_js(drupal_get_path("module", "kickapps")."/kickapps.admin.js");

		$fieldname = 'team_name';
		$fieldid = 'team_id';
		$table = 'hope_team';
		$comp = '1';
		$parent = 'troop_id';


	$sQlteam = "SELECT *
				FROM {hope_team}
				WHERE {team_id} = %d";
	$oResult = db_query($sQlteam, $id);

	$oRes = db_fetch_object($oResult);
	mysqli_free_result($oResult);
	$teamname = $oRes->team_name;
	$teamid = $oRes->team_id;
	$kickappsid = $oRes->kickappsteam_id;
	$team_color = str_replace("#", '', $oRes->team_color);

				$sOutput .= '
					 <div id="statusMsg">&nbsp;</div>
						<div>
						<div style="width:100%;">
							<div style="float:left;">
								Team Name: <br/><input type="text" id="teamtitleName" name="teamtitleName" value="'.$teamname.'"/> <br/><br/>
								Kickapps Team ID:  <br/><input type="text" id="teamKID" name="teamKID" value="'.$kickappsid.'"/><br/><br/>
								Color:<sup></sup><br/>
								<select id="teamColor" name="teamColor"><option>&nbsp;</option>';
								$arr_teamcolor = array('Red'=>'cc2200','White'=>'ffffff','Blue'=>'0006e5','Gold'=>'7d6c12');
								foreach($arr_teamcolor as $titlecolor => $color){
									if($color == $team_color){
									$sOutput .= '<option value="'.$color.'" selected>'.$titlecolor.'</option>';
									} else{
									$sOutput .= '<option value="'.$color.'">'.$titlecolor.'</option>';
									}
								}
				$sOutput .= '</select>';


				$sOutput .= '</div>
							<div style="float:right;" id="teams_announce_div">
									<br/><b>Announcement & News</b> <label id="loadingpost" style="display:none;">Loading..</label><br/>
									<div style="height: 50px;width: 300px;overflow: auto;border: 1px solid #666;background-color: #ededed;padding: 8px;" id="announce_messages">';

									$sqlAnnounce = "SELECT teamnews_id, team_id, announce_text, announce_date
													FROM hope_team_news
													WHERE team_id = %d
													ORDER BY teamnews_id DESC
													";
										$oAnnounceResult = db_query($sqlAnnounce, $kickappsid);

										$sOutput .= '';
										$Annoucnecount = 0;
										while ($oAnnounce = db_fetch_object($oAnnounceResult)){
											$sOutput .= $oAnnounce->announce_text.' <span style="font-size:10px;"><b>'.date("F j, Y, g:i a", $oAnnounce->announce_date).'  <a href="javascript:void(0);" onclick="team_announcement_remove(\''.$oAnnounce->teamnews_id.'\',\''.$teamid.'\');">[remove]</a></b></span><br/><br/>';
										$Annoucnecount++;
										}
										mysqli_free_result($oAnnounceResult);
										if($Annoucnecount == 0){
											$sOutput .= "No post yet.";
										}

						$sOutput .= '</div>
									<div>&nbsp;</div>
									<textarea id="team_announcement_textarea" name="team_announcement_textarea" cols=40 rows=4></textarea>
									<div>&nbsp;</div>
									<input type="button" value="Post a Message" id="team_announcement_submit" id="team_announcement_submit" onclick="team_announcement_submit(\''.$kickappsid.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"/>
							</div>
							<div style="clear:both;"></div>
								<br/>
								<br/>
									<div style="float:left;"><input type="button" value="Update Team" onclick="UpdateTeam(\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"> <!--<input type="button" value="Delete" onclick="deleteTeam(\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">-->
									</div>
									<div style="float:right;">
									   <input type="button" id="showSelectionMemberList" name="showSelectionMemberList" onclick="showSelectionMemberList();" value="Display Member List" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"> <input type="button"  value="Remove Member" onclick="removeMember(\''.$kickappsteam_id.'\');"class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
									</div>
									<div style="clear:both;">&nbsp;</div>
								</div>

							<div style="display:none;">
									<div style="width:100%;">
										Name: <br/>
										<input type="text" id="edittitleName" name="edittitleName" value="'.$teamname.'"/>
										<input type="hidden" id="edittitleID" name="edittitleID" value="'.$teamid.'"/>
										<input type="button" value="Update" onclick="UpdateTeam(\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
										<input type="button" value="Delete" onclick="deleteTeam(\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
									</div>
									<div>&nbsp;</div>
							</div>';

				$sOutput .= '<div id="memberRes">'.kickapps_MembersRes($kickappsid)."</div>";

				$sOutput .= '<div id="memberSelectList" style="display:none;">';

							$sqlTeamHopful = db_query("SELECT uid
									FROM hope_teamusers");
							$arr_teamhopeful = array();
							while ($TeamHopeful = db_fetch_object($sqlTeamHopful)){
							$arr_teamhopeful[] = $TeamHopeful->uid;
							}
							mysqli_free_result($sqlTeamHopful);
							$team_hopefuls = implode(',',$arr_teamhopeful);

							$querycheck = _kickapps_team_volunteer_or_hopeful($kickappsid);

								$sqlAvailableHopful = "SELECT B.uid, B.name
									FROM users_roles A
									INNER JOIN users B ON B.uid = A.uid
									WHERE {$querycheck}
									AND B.uid not in(".$team_hopefuls.")
									ORDER BY B.name";

							$oAvailableHopfulResult = db_query($sqlAvailableHopful);
							$sUnassigned = '';

							while ($oAvailableHopeful = db_fetch_object($oAvailableHopfulResult)){
								$sAssignedTo = ($oAvailableHopeful->iAssignedId == "") ? 'unassigned':$oAvailableHopeful->sAssignedName;
								$sUnassigned .= '<option value="'.$oAvailableHopeful->uid.'"'.(($oAvailableHopeful->iAssignedId == "") ? ' style="font-weight:bold;':'').'">'.$oAvailableHopeful->name.'</option>';
							}
							mysqli_free_result($oAvailableHopfulResult);
							if ($sUnassigned == ''){
								$sUnassigned = '<option value="">There are no available hopefuls.</option>';
							}

				$sOutput .= '<div id="teams_available_hopeful_div"><select id="teams_available_hopeful" name="teams_available_hopeful[]" size="10" style="width:275px; margin-top:5px;" multiple="multiple">'.$sUnassigned.'</select></div><br/><input type="button" name="btnaddhopeful" id="btnaddhopeful" onclick="btnaddhopeful(\''.$kickappsid.'\');" value="add member"  class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"/>';
				$sOutput .= "</div>";

	echo json_encode(array("STATUS" => 'Success', "OUTPUT" => $sOutput));
}

function kickapps_fill_dropdown_teamhopeful($teamid){

	$sqlTeamHopful = db_query("SELECT uid FROM hope_teamusers");
	$arr_teamhopeful = array();
	while ($TeamHopeful = db_fetch_object($sqlTeamHopful)){
		$arr_teamhopeful[] = $TeamHopeful->uid;
	}
	mysqli_free_result($sqlTeamHopful);
	$team_hopefuls = implode(',',$arr_teamhopeful);
	$oAvailableHopfulResult = db_query($sqlAvailableHopful);

	$querycheck = _kickapps_team_volunteer_or_hopeful($teamid);

	$sqlAvailableHopful = "SELECT B.uid, B.name
									FROM users_roles A
									INNER JOIN users B ON B.uid = A.uid
									WHERE {$querycheck}
									AND B.uid not in(".$team_hopefuls.")
									ORDER BY B.name";

	$oAvailableHopfulResult = db_query($sqlAvailableHopful);
	$sUnassigned = '';

	while ($oAvailableHopeful = db_fetch_object($oAvailableHopfulResult)){
		$sAssignedTo = ($oAvailableHopeful->iAssignedId == "") ? 'unassigned':$oAvailableHopeful->sAssignedName;
		$sUnassigned .= '<option value="'.$oAvailableHopeful->uid.'"'.(($oAvailableHopeful->iAssignedId == "") ? ' style="font-weight:bold;':'').'">'.$oAvailableHopeful->name.'</option>';
	}
	mysqli_free_result($oAvailableHopfulResult);

	if ($sUnassigned == ''){
		$sUnassigned = '<option value="">There are no available hopefuls.</option>';
	}

 return $sUnassigned;
}

function _kickapps_team_volunteer_or_hopeful($team_id){

	$sqlCheckDiv = "SELECT F.div_id
					FROM hope_team B
					LEFT JOIN hope_troop C ON C.troop_id = B.troop_id
					LEFT JOIN hope_wing D ON D.wing_id = C.wing_id
					LEFT JOIN hope_group E ON E.group_id = D.group_id
					LEFT JOIN hope_division F ON F.div_id = E.div_id
					WHERE B.kickappsteam_id = %d";

	$oDetailsResult = db_query($sqlCheckDiv, $team_id);
	$oDetails = db_fetch_object($oDetailsResult);
	mysqli_free_result($oDetailsResult);
	$div_id = $oDetails->div_id;

	if($div_id == 2){
	return 'A.rid != 9';
	} else{
	return 'A.rid = 9';
	}
}

function kickapps_MembersRes($kickappsteam_id){

$sQlchild = "SELECT A.team_userid, C.name
							FROM hope_teamusers A
							LEFT JOIN users C ON C.uid = A. uid
							WHERE A.team_id = %d";
		$ochildResult = db_query($sQlchild, $kickappsteam_id);

		$sOutput = '<form id="childForm" name="childForm"><div style="clear:both;">
									<div style="float:left; width:10%;">&nbsp;</div>
									<div style="float:left; width:20%;">ID</div>
									<div style="float:left; width:20%;">Name</div>
									<div style="float:left; width:50%;">&nbsp;</div>
								</div>
								<div>&nbsp;</div>
								<span style="display:none;"><input type="radio" id="inputChild" name="inputChild" value=""></span>';

				$bg_colors = array(0 => '#f0f0f0', 1 => '#d0d0d0');
				$c = 0;
				$ctr = 1;
				while($ochildRes = db_fetch_object($ochildResult)){

					$sOutput .= '<div style="width:100%;">
										<div style="float:left;height:30px;width:10%;background-color:'.$bg_colors[$c].'">&nbsp;&nbsp;<input type="radio" id="inputChild" name="inputChild" value="'.$ochildRes->team_userid.'_'.$kickappsteam_id.'"></div>
										<div style="float:left;height:30px;width:20%;background-color:'.$bg_colors[$c].'">'.$ochildRes->team_userid.'</div>
										<div style="float:left;height:30px;width:70%;background-color:'.$bg_colors[$c].'">'.$ochildRes->name.'</div>
								</div>';
					if($c == 0){
					$c = 1;
					}else{
					$c = 0;
					}
				$ctr++;
				}
				mysqli_free_result($ochildResult);
		$sOutput .= '</form>';
		if($ctr == 1){
		$sOutput = 'No members yet';
		}

return $sOutput;
}

function kickapps_manage_content($type, $id){
	drupal_add_js(drupal_get_path("module", "kickapps")."/kickapps.admin.js");
	switch($type){
	case 'div':
		$fieldname = 'div_name';
		$fieldid = 'div_id';
		$table = 'hope_division';
		$comp = '1';
		$childid = 'group_id';
		$childname = 'group_name';
		$childtbl = 'hope_group';
		$child = 'group';
	break;
	case 'group':
		$fieldname = 'group_name';
		$fieldid = 'group_id';
		$table = 'hope_group';
		$comp = '1';
		$childid = 'wing_id';
		$childname = 'wing_name';
		$childtbl = 'hope_wing';
		$child = 'wing';
	break;
	case 'wing':
		$fieldname = 'wing_name';
		$fieldid = 'wing_id';
		$table = 'hope_wing';
		$comp = '1';
		$childid = 'troop_id';
		$childname = 'troop_name';
		$childtbl = 'hope_troop';
		$child = 'troop';
	break;
	case 'troop':
		$fieldname = 'troop_name';
		$fieldid = 'troop_id';
		$table = 'hope_troop';
		$comp = '1';
		$childid = 'team_id';
		$childname = 'team_name';
		$childtbl = 'hope_team';
		$child = 'team';
	break;
	case 'team':
		$fieldname = 'team_name';
		$fieldid = 'team_id';
		$table = 'hope_team';
		$comp = '1';
		$parent = 'troop_id';
	break;
	}

	if($comp == 1){
	$sQl = "SELECT {$fieldid}, {$fieldname}
				FROM {$table}
				WHERE {$fieldid} = %d";
	$oResult = db_query($sQl, array($id));
	$oRes = db_fetch_object($oResult);
	mysqli_free_result($oResult);
	$name = $oRes->$fieldname;

	$sOutput = '<div>
					<div>
						<span id="statusMsg">&nbsp;</span>
					</div>
					<div style="clear:both;">
						Title: <input type="text" id="titleName" name="titleName" value="'.$name.'"/>
						<input type="button" value="Update" onclick="UpdateTitle(\''.$id.'\',\''.$type.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
						<input type="button" id="deleteCategory" name="deleteCategory" value="Remove" onclick="deleteCategory(\''.$type.'\',\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"/>
					</div><div>&nbsp;</div>';

				$sQlchild = "SELECT {$childid}, {$childname}
							FROM {$childtbl}
							WHERE {$fieldid} = %d";
				$ochildResult = db_query($sQlchild, array($id));

				$sOutput .= '<div>&nbsp;</div>
							<div>';
					$sOutput .= '<div>&nbsp;</div><div id="ChildDiv" style="display:none;"><div style="width:100%;">Name: <input type="text" id="ctitleName" name="ctitleName" value=""/> <input type="button" value="Save" onclick="addNewCategory(\''.$child.'\',\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"></div><div>&nbsp;</div></div>';
					$sOutput .= '<div id="TeamDiv" style="display:none;"><div style="width:100%;">Team Name: <br/><input type="text" id="teamtitleName" name="teamtitleName" value=""/> <br/><br/>Kickapps Team ID:  <br/><input type="text" id="teamKID" name="teamKID" value=""/><br/><br/>Color:<sup>*#000000</sup><br/>#<input type="text" id="teamColor" name="teamColor" value=""/><br/><br/><input type="button" value="Add team" onclick="addNewCategory(\''.$child.'\',\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"></div><div>&nbsp;</div></div>';
					//$sOutput .= '<div id="EditChildDiv" style="display:none;"><div style="width:100%;"><input type="text" id="edittitleName" name="edittitleName" value=""/><input type="hidden" id="edittitleID" name="edittitleID" value=""/> <input type="button" value="Update" onclick="UpdateTitleEach(\''.$child.'\',\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"></div><div>&nbsp;</div></div>';
					$sOutput .= '<div style="clear:both;">
									<div style="float:left; width:10%;">&nbsp;</div>
									<div style="float:left; width:20%;">ID</div>
									<div style="float:left; width:20%;">Name</div>
									<div style="float:left; width:50%;"><input type="button" value="Add" onclick="addNewChild(\''.$child.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
																		<input type="button" value="Edit" onclick="editChild();" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
																		<input type="button"  value="Delete" onclick="deleteChild(\''.$child.'\');"class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"></div>
								</div>
								<div>&nbsp;</div>';

					$sOutput .= '<form id="childForm" name="childForm" method="post"><div id="childRes">';
					$bg_colors = array(0 => '#f0f0f0', 1 => '#d0d0d0');
					$c = 0;
					$ctr = 1;
					while($ochildRes = db_fetch_object($ochildResult)){

						$sOutput .= '<div style="width:100%;">
										<div style="float:left;height:30px;width:10%;background-color:'.$bg_colors[$c].'">&nbsp;&nbsp;<input type="radio" id="inputChild" name="inputChild" value="'.$ochildRes->$childid.'_'.$ochildRes->$childname.'"></div>
										<div style="float:left;height:30px;width:20%;background-color:'.$bg_colors[$c].'">'.$ochildRes->$childid.'</div>
										<div style="float:left;height:30px;width:70%;background-color:'.$bg_colors[$c].'"><span id="text_'.$ochildRes->$childid.'">'.$ochildRes->$childname.'</span> <div id="input_'.$ochildRes->$childid.'" style="display:none;"><input type="text" id="edittitleName_'.$ochildRes->$childid.'" name="edittitleName_'.$ochildRes->$childid.'" value=""/><input type="hidden" id="edittitleID_'.$ochildRes->$childid.'" name="edittitleID_'.$ochildRes->$childid.'" value=""/> <input type="button" value="Update" onclick="UpdateTitleEach(\''.$ochildRes->$childid.'\',\''.$child.'\',\''.$id.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"></div></div>
									</div>';
						if($c == 0){
						$c = 1;
						}else{
						$c = 0;
						}
					$ctr++;
					}
					mysqli_free_result($ochildResult);
					if($ctr == 1){
					$sOutput .= '<div style="width:100%;">There are no items yet.</div>';
					}
					$sOutput .= '</div></form>';
				$sOutput .= '</div>';

	$sOutput .= '</div>';
	} else{

	$sOutput = '';

	}

	echo json_encode(array("STATUS" => 'Success', "OUTPUT" => $sOutput));
}

function kickapps_manage_group(){
 $sHtml = '
<link type="text/css" rel="stylesheet" media="all" href="http://jqueryui.com/themes/base/jquery.ui.all.css" />
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.core.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.widget.js"></script>
<script type="text/javascript" src="http://jqueryui.com/ui/jquery.ui.tabs.js"></script>
<link type="text/css" rel="stylesheet" media="all" href="http://jquery.bassistance.de/treeview/jquery.treeview.css" />
<link type="text/css" rel="stylesheet" media="all" href="http://jqueryui.com/demos/demos.css" />';


drupal_add_js(drupal_get_path("module", "mystudies")."/jquery-ui.js");
drupal_add_js(drupal_get_path("module", "mystudies")."/jquery.treeview.async.js");
drupal_add_js(drupal_get_path("module", "mystudies")."/jquery.treeview.js");
drupal_add_js(drupal_get_path("module", "kickapps")."/kickapps.admin.js");

drupal_add_css(drupal_get_path("module", "mystudies")."/jquery-ui-custom.css");

$sHtml .= '
<div class="demo">
<div id="userKickappstabs">
    <ul>
		<li><a href="#tabs-1">Heirarchy</a></li>

		<li><a href="#tabs-2">Users</a></li>

		<!--<li><a href="#tabs-2">Request</a></li>-->
	</ul>
	<div id="tabs-1">
		<input type="button" id="adddivision" name="adddivision" value="add new division" onclick="openDivisionDialog();" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" /> <input type="button" id="refreshpage" name="refreshpage" value="refresh" onclick="window.location='."'http://www.hopecybary.org/admin/kickapps/manage';".'" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" />
		<br/><br/><b>Root</b>';

	$sqlDiv = "SELECT A.div_id, A.div_name
				FROM hope_division A";
	$oDivResult = db_query($sqlDiv);

    $sHtml .= '<ul id="division_CatList">';
	$divCount = 1;
	while ($oDiv= db_fetch_object($oDivResult)){

	$sHtml .= '<li class="closed"><span>'.$divCount.'.) '.$oDiv->div_name.'</span> <sup><a href="javascript:void(0);" onclick="manageContents(\''."div".'\',\''.$oDiv->div_id.'\');"><i>Manage</i></a></sup>';

		$sqlGroup = "SELECT A.group_id, A.group_name
				FROM hope_group A
				WHERE div_id = %d";

		$oGroupResult = db_query($sqlGroup, array($oDiv->div_id));

		$sHtml .= '<ul>';
		$divGroup = 1;
		while ($oGroup = db_fetch_object($oGroupResult)){

			$sHtml .= '<li class="closed"><span>'.$divCount.'.'.$divGroup.'.) '.$oGroup->group_name.'</span> <sup><a href="javascript:void(0);" onclick="manageContents(\''."group".'\',\''.$oGroup->group_id.'\');"><i>Manage</i></a></sup>';
				$sqlWing = "SELECT A.wing_id, A.wing_name
					FROM hope_wing A
					WHERE group_id = %d";

				$oWingResult = db_query($sqlWing, array($oGroup->group_id));
				$sHtml .= '<ul>';
				$divWing = 1;
				while ($oWing = db_fetch_object($oWingResult)){
					$sHtml .= '<li class="closed"><span>'.$divCount.'.'.$divGroup.'.'.$divWing.'.) '.$oWing->wing_name.'</span> <sup><a href="javascript:void(0);" onclick="manageContents(\''."wing".'\',\''.$oWing->wing_id.'\');"><i>Manage</i></a></sup>';

					$sqlTroop = "SELECT A.troop_id, A.troop_name
									FROM hope_troop A
									WHERE wing_id = %d";
					$oTroopResult = db_query($sqlTroop, array($oWing->wing_id));
					$sHtml .= '<ul>';
					$divTroop = 1;
						while ($oTroop = db_fetch_object($oTroopResult)){
							$sHtml .= '<li class="closed"><span>'.$divCount.'.'.$divGroup.'.'.$divWing.'.'.$divTroop.'.) '.$oTroop->troop_name.'</span> <sup><a href="javascript:void(0);" onclick="manageContents(\''."troop".'\',\''.$oTroop->troop_id.'\');"><i>Manage</i></a></sup>';
								$sqlTeam = "SELECT A.team_id, A.team_name
									FROM hope_team A
									WHERE troop_id = %d";
								$oTeamResult = db_query($sqlTeam, array($oTroop->troop_id));
								$sHtml .= '<ul>';
								$divTeam = 1;
								while ($oTeam = db_fetch_object($oTeamResult)){
									$sHtml .= '<li><span>'.$divCount.'.'.$divGroup.'.'.$divWing.'.'.$divTroop.'.'.$divTeam.'.) '.$oTeam->team_name.'</span> <sup><a href="javascript:void(0);" onclick="manageTeamContents(\''.$oTeam->team_id.'\');"><i>Manage</i></a></sup></li>';
								$divTeam++;
								}
								mysqli_free_result($oTeamResult);
								$sHtml .= '</ul>';
							$sHtml .= '</li>';
						$divTroop++;
						}
						mysqli_free_result($oTroopResult);
					$sHtml .= '</ul>';

					$sHtml .= '</li>';
				$divWing++;
				}
				mysqli_free_result($oWingResult);
				$sHtml .= '</ul>';
			$sHtml .= '</li>';
		$divGroup++;
		}
		mysqli_free_result($oGroupResult);
		$sHtml .= '</ul>';

	$sHtml .= '</li>';
	$divCount++;
	}
	mysqli_free_result($oDivResult);
	$sHtml .= '</ul>';

	$sHtml .= '</div>
	<div id="tabs-2">
		<h3>Users</h3>';

	$sHtml .= kickapps_loadusertable();

	$sHtml .= '</div>
</div>
	<div id="manage_Dialog" title="Manage Hierarchy" style="display:none;"><div id="manageContent">&nbsp;</div></div>
	<div id="manageTeam_Dialog" title="Manage Team" style="display:none;"><div id="manageTeamContent">&nbsp;</div></div>
	<div id="division_Dialog" title="Add New Division" style="display:none;"><div><span id="statusMsg">&nbsp;</span></div><div>Title: <input type="text" id="atitleName" name="atitleName" value="'.$name.'"/> <input type="button" value="Add" onclick="addNewCategoryDiv(\''.'div'.'\');" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"></div></div>';

 return $sHtml;
}

function kickapps_loadusertable(){

	if($_GET['page']){
	$sJavaScript = '$(document).ready(
								function(){
									$("#userKickappstabs").tabs("select", "2");
								}
							)';

	drupal_add_js($sJavaScript, "inline");
	}

	$sqlUsers = "SELECT B.name, A.uid
					FROM hope_assign_users A
					INNER JOIN users B ON B.uid = A.uid";
	$sqlCount = "SELECT COUNT(B.name)
					FROM hope_assign_users A
					INNER JOIN users B ON B.uid = A.uid";


	$sTableContent .= '<table style="width:680px;"><tr style="font-size:0.8em;">
								<th class="select-all" style="padding:5px;"><!--<input type="checkbox" id="kindness_master_admin_bCheckAll" name="kindness_master_admin_bCheckAll" title="Select all rows in this table" />-->&nbsp;</th>
								<th style="width:20%;">Username</th>
								<th style="width:10%;">Status</th>
								<th style="width:15%;text-align:center;">Division</th>
								<th style="width:15%;text-align:center;">Group</th>
								<th style="width:15%;text-align:center;">Wing</th>
								<th style="width:10%;text-align:center;">Troop</th>
								<th style="width:15%;text-align:center;">Team</th>
							</tr>';

	$sqlUsers = sprintf($sqlUsers);
	$sqlCount = sprintf($sqlCount);
	$iMaxRec = 25;
	$oUsersResult = pager_query($sqlUsers, $iMaxRec, 0, $sqlCount);
	$bg_colors = array(0 => '#f0f0f0', 1 => '#d0d0d0');
	$c = 0;
	while ($oUsers = db_fetch_object($oUsersResult)){
		$iUserId = $oUsers->uid;
		$sName = $oUsers->name;
		$array_status = kickapps_status($iUserId);
		$status = $array_status[0];
		$division = $array_status[1];
		$group = $array_status[2];
		$wing = $array_status[3];
		$troop = $array_status[4];
		$team = $array_status[5];

		$sTableContent .= '<tr style="background-color:'.$bg_colors[$c].'" style="font-size:0.8em;">
								<td style="padding-top:3px; vertical-align:top;text-align:center;"><!--<input type="checkbox" />-->&nbsp;</td>
								<td style="padding-top:3px; vertical-align:top;text-align:left;">'.$sName.'</td>
								<td style="padding-top:3px; vertical-align:top;text-align:center;font-size:10px;">'.$status.'</td>
								<td style="padding-top:3px; vertical-align:top;text-align:center;font-size:10px;">'.$division.'</td>
								<td style="padding-top:3px; vertical-align:top;text-align:center;font-size:10px;">'.$group.'</td>
								<td style="padding-top:3px; vertical-align:top;text-align:center;font-size:10px;">'.$wing.'</td>
								<td style="padding-top:3px; vertical-align:top;text-align:center;font-size:10px;">'.$troop.'</td>
								<td style="padding-top:3px; vertical-align:top;text-align:center;font-size:10px;">'.$team.'</td>
							</tr>';
		if($c == 0){
		$c = 1;
		}else{
		$c = 0;
		}
	$Count++;
	$iCount++;
	}
	mysqli_free_result($oUsersResult);
	$sTableContent .= '</table>';

	if($Count == 1){
	$sTableContent .= 'No users have selected a team yet.';
	}

	//$sPagerHTML = ($sTableContent != "No users have selected a team yet.") ? '<br/><br/>'.theme("pager", null, $iMaxRec):'';
	$sPagerHTML = '<br/><br/>'.theme("pager", null, $iMaxRec);

	return $sTableContent.$sPagerHTML;
}

function kickapps_status($userID){

	$sqlUsers = "SELECT count(team_userid) as userscount
					FROM hope_teamusers
				WHERE uid = %d";

	$oTeamResult = db_query($sqlUsers,  array($userID));
	$oTeam = db_fetch_object($oTeamResult);
	mysqli_free_result($oTeamResult);
	$array_res = array();

	if($oTeam->userscount == 0){
	array_push($array_res, 'Unassigned', '-', '-', '-', '-', '-');
	} else{
		$sqlTeam = "SELECT B.team_id, B.team_name, B.troop_id
					FROM hope_teamusers A
					INNER JOIN hope_team B ON B.kickappsteam_id = A.team_id
					WHERE A.uid = %d";

		$aTeamResult = db_query($sqlTeam,  array($userID));
		$aTeam = db_fetch_object($aTeamResult);
		mysqli_free_result($aTeamResult);
		$sqlTroop = "SELECT A.wing_id, A.troop_name
					FROM hope_troop A
					WHERE A.troop_id = %d";

		$aTroopResult = db_query($sqlTroop,  array($aTeam->troop_id));
		$aTroop = db_fetch_object($aTroopResult);
		mysqli_free_result($aTroopResult);

		$sqlWing = "SELECT A.group_id, A.wing_name
					FROM hope_wing A
					WHERE A.wing_id = %d";

		$aWingResult = db_query($sqlWing,  array($aTroop->wing_id));
		$aWing = db_fetch_object($aWingResult);
		mysqli_free_result($aWingResult);

		$sqlGroup = "SELECT div_id, group_name
					FROM hope_group
					WHERE group_id = %d";

		$aGroupResult = db_query($sqlGroup,  array($aWing->group_id));
		$aGroup = db_fetch_object($aGroupResult);
		mysqli_free_result($aGroupResult);

		$sqlDiv = "SELECT div_name
					FROM hope_division
					WHERE div_id = %d";

		$aDivResult = db_query($sqlDiv,  array($aGroup->div_id));
		$aDiv = db_fetch_object($aDivResult);
		mysqli_free_result($aDivResult);

	array_push($array_res, 'Member', $aDiv->div_name, $aGroup->group_name, $aWing->wing_name, $aTroop->troop_name, $aTeam->team_name);
	}

return $array_res;
}

function kickapps_loadteamtable($troopid){

	$sqlTeam = "SELECT A.kickappsteam_id, A.team_name, A.team_color, A.team_type
				FROM hope_team A
				WHERE troop_id = %d";
	$oTeamResult = db_query($sqlTeam,  array($troopid));

	$sOutput = '<tr>';
	while ($oTeam = db_fetch_object($oTeamResult)){

	$sOutput .= '<td style="text-align:center; width:215px; heigh:315px; padding-bottom:10px;">
		               <div style="margin:2px; 2px; 2px; 2px;padding-top:12px; padding-bottom:12px;background-color: #FFFFFF !important; background-image: none; border: 1px solid #cdcdcd !important; #000000 !important; font-size: 12px;"">
						<div style="width:165px;"><a href="'.$base_url.'/community?m=team&id='.$oTeam->kickappsteam_id.'"><span style="border:1px solid black;padding: 0;margin: 8px 5px 3px;display: block;width:163px;height:20px;background:#'.$oTeam->team_color.' no-repeat center center"></span></a></div>
						<div id="name_373" style="text-align:left;padding-left:8px;"><a href="'.$base_url.'/community?m=team&id='.$oTeam->kickappsteam_id.'"><b>'.$oTeam->team_name.'</b></a><br/><b>Members</b>: '.kickapps_teamcount($oTeam->kickappsteam_id).'</div>
					   </div>
					</td>';
	}
	mysqli_free_result($oTeamResult);
	$sOutput .= '</tr>';

	$sqlTr = "SELECT A.troop_id, A.troop_name, B.wing_name, C.group_name
				FROM hope_troop A
				INNER JOIN hope_wing B ON B.wing_id = A.wing_id
				INNER JOIN hope_group C ON C.group_id = B.group_id
				WHERE A.troop_id = %d";

	$oTrResult = db_query($sqlTr,  array($troopid));
	$oTr = db_fetch_object($oTrResult);
	mysqli_free_result($oTrResult);
	$sCurrpath = 'Location : '.$oTr->group_name.' -> '.$oTr->wing_name.' -> '.$oTr->troop_name;

	echo json_encode(array("STATUS" => 1, "Output" => $sOutput, "Path" => $sCurrpath));
}

function kickapps_assignteam($teamid, $userid, $task){
/*
  switch($task){
  case 'join':
	$sqlInsert = "INSERT INTO hope_teamusers VALUES(NULL, %d, %d, NULL, NULL)";
	db_query($sqlInsert, array($teamid, $userid));
  break;
  case 'leave':
	$sqlDelete = "DELETE FROM hope_teamusers WHERE team_id = %d AND uid = %d";
	db_query($sqlDelete, array($teamid, $userid));
  break;
  case 'update':
	$sqlUpdate = "UPDATE hope_teamusers
					SET status = NULL,
					team_id = %d
					WHERE uid = %d";
	db_query($sqlUpdate, array($teamid, $userid));
  break;
  } */

  switch($task){
  case 'join':
	$sqlInsert = "UPDATE hope_teamusers SET status = 1 WHERE uid = %d";
	db_query($sqlInsert, array($userid));
  break;
  case 'leave':
	$sqlDelete = "DELETE FROM hope_teamusers WHERE team_id = %d AND uid = %d";
	db_query($sqlDelete, array($teamid, $userid));
  break;
  case 'update':
	$sqlUpdate = "UPDATE hope_teamusers
					SET status = NULL,
					team_id = %d
					WHERE uid = %d";
	db_query($sqlUpdate, array($teamid, $userid));
  break;
  }

  echo json_encode(array("STATUS" => 1, "RETURN" => TRUE));
}

function kickapps_community(){
    $sOutput = 'Page Under Contruction.';

    return $sOutput;
}

function kickapps_home() {
    global $user;

    if ($user->uid){

        $header = '
            <div class="jbox">
            <div class="jboxhead">
            <h2></h2>
            </div>
            <div class="jboxbody">
            <div class="jboxcontent">
                  <div id="ka_header" class="clearfix">
                    <div id="ka_headerTopNav" style="display:block;font-size:15px;font-weight:bold;">
                    <ul id="ka_headerTopNav_ul">
                    <li>
                    <a href="community">
                    <span>dashboard</span>
                    </a>
                    </li>
                    <li>
                    <a href="community/videos">
                    <span>videos</span>
                    </a>
                    </li>
                    <li>
                    <a href="community/photos">
                    <span>photos</span>
                    </a>
                    </li>
                    <li>
                    <a href="community/blogs">
                    <span>blogs</span>
                    </a>
                    </li>
                    <li>
                    <a href="community/members">
                    <span>members</span>
                    </a>
                    </li>
                    <li>
                    <a href="community/teams">
                    <span>teams</span>
                    </a>
                    </li>
                    </ul>
                    </div></div></div></div>
                <div class="jboxfoot">
               <p></p>
               </div>
              </div>';

        $sOutput = '<div id="ka_header" class="clearfix">
                        <div id="ka_headerTopNav" style="display:block;font-size:15px;">
                            <ul id="ka_headerTopNav_ul">
                                <li><a href="community/profile">My Profile</a></li>
                                <li><a href="community/account">My Account</a></li>
                            </ul>
                         </div>
                    </div>';

        $sOutput .= '<table width="100%" cellspacing="0" cellpadding="0" border="0">
					<tbody><tr>
						<td width="670">
							<div id="">
								<div class=""><div class="i1"><div class="i2"><div class="i3">
									<div class="jboxh">
                                        <div class="jboxhead"><h2 style="color:#4d8da1; font-weight:normal;">Latest Activity</h2></div>
                                        <div class="jboxbody">
                                            <div class="jboxcontent" style="padding:5px 10px 5px 5px">
                                               No activites yet.
                                            </div>
                                        </div>
                                        <div class="jboxfoot"><p></p></div>
                                    </div>
								</div></div></div><div class="bb"><div></div></div></div>
							</div>

                            </td>

				<td style="padding:3px 2px 3px 5px;">
                        	<div id="cybrary_right">
                            	<div class="jboxh">
                                    <div class="jboxhead"><h2 style="color:#4d8da1; font-weight:normal;">Latest Blogs</h2></div>
                                    <div class="jboxbody">
                                        <div class="jboxcontent">
                                            No blogs yet.
                                        </div>
                                    </div>
                                    <div class="jboxfoot"><p></p></div>
                                </div>
                            	<hr class="divider">
                                <div class="jboxh">
                                    <div class="jboxhead"><h2 style="color:#4d8da1; font-weight:normal;">Latest Videos</h2></div>
                                    <div class="jboxbody">
                                        <div class="jboxcontent">
                                            No videos yet.
                                        </div>
                                    </div>
                                    <div class="jboxfoot"><p></p></div>
                                </div>
                            	<hr class="divider">
                                <div class="jboxh">
                                    <div class="jboxhead"><h2 style="color:#4d8da1; font-weight:normal;">Latest Photos</h2></div>
                                    <div class="jboxbody">
                                        <div class="jboxcontent">
                                            No photos yet.
                                        </div>
                                    </div>
				    <div class="jboxfoot"><p></p></div>
                                </div>
                            	<hr class="divider">
                                <div class="jboxh">
					<div class="jboxhead"><h2 style="color:#4d8da1; font-weight:normal;">Teams</h2></div>
						<div class="jboxbody">
							<div class="jboxcontent">
								No teams yet.
							</div>
						</div>
					<div class="jboxfoot"><p></p></div>
                                </div>
                            	<hr class="divider">
                            </div>
                        </td>
		</tr>
	</tbody></table>';

        } else{

        $sOutput = '<div class="jbox">
            <div class="jboxhead">
            <h2></h2>
            </div>
            <div class="jboxbody">
            <div class="jboxcontent">
                  <div id="ka_header" class="clearfix">
                    <div id="ka_headerTopNav" style="display:block;font-size:15px;font-weight:bold;">
                    Please login to enter the cybrary community.
                    </div></div></div></div>
                <div class="jboxfoot">
               <p></p>
               </div>
              </div>';

        }

        return $header.$sOutput;
}

function kickapps_teamcount($kickappsgroup_id){
	$sqlCount= "SELECT count(A.team_userid) as count_members
				FROM hope_teamusers A
				WHERE team_id = %d";
	$oCountResult = db_query($sqlCount,  array($kickappsgroup_id));
	$oCount = db_fetch_object($oCountResult);
	mysqli_free_result($oCountResult);

	return $oCount->count_members;
}

function kickapps_teams_volunteer(){
global $user;

	$csS = 'kickapps_theme2010';

	if($_GET['css'] == $csS){
	$sHeader = drupal_eval(load_kickapps_template('page-team-volunteer'));
    } else{
	$sHeader = drupal_eval(load_kickapps_template('page-team-hopefuls'));
	}

	$sOutput = '<div><center><h3>HopeNet Teams</h3></center></div>';

	$sOutput .= '<div style="background-color:#ffffff;">
					<center>
					<img src="'.$base_url.'/themes/theme2010/images/gi_teams_1.jpg" />
					</center>
					<div style="width:400px;padding-left:170px;">Teamwork is crucial to the success of HopeNet and because of this HopeNet has organized both the Hopefuls and its volunteers into teams.</div>

					<div style="clear:both;background-color:#ffffff;">&nbsp;</div>
					<div style="background-color:#ffffff;padding-left:30px;">
						<div style="float:left;"><img src="'.$base_url.'/themes/theme2010/images/gi_teams_2.jpg" />
						<center>To learn more about the Volunteer Teams <br/> <a href="/community/volunteerteams" style="text-decoration:none;"><b style="color:black;">Please Click Here</b></a></center>
						</div>
						<div style="float:left;width:100px;">&nbsp;</div>
						<div style="float:left;"><img src="'.$base_url.'/themes/theme2010/images/gi_teams_3.jpg" />
						<center>To learn more about the Hopeful Teams <br/> <a href="#" style="text-decoration:none;"><b style="color:black;">Please Click Here</b></a></center>
						</div>
					</div>
			  </div>
			  ';

	$sFooter = '
	</div><div style="height:50px;">&nbsp;</div>
</div></body></html>';

	return $sHeader.$sOutput.$sFooter;
}

function kickapps_volunteerteams(){

	$sHeader = drupal_eval(load_kickapps_template('page-team-volunteer'));

	$sOutput = '<div><center><h3>Volunteer Teams</h3></center></div>';

	$sOutput .= '<div style="background-color:#ffffff;">
					<center>
					<img src="'.$base_url.'/themes/theme2010/images/gi_volunteer_standout.jpg" />
					</center>
					<div style="clear:both;background-color:#ffffff;padding-left:100px;"><img src="'.$base_url.'/themes/theme2010/images/gi_volunteer_corps_line.jpg" /></div>
					<div style="background-color:#ffffff;padding-left:10px;">
						<div style="float:left;"><img  style="cursor:pointer;" src="'.$base_url.'/themes/theme2010/images/gi_offline_volunteer_unit.jpg" onclick=window.location="'.$base_url.'/community/offlinevolunteerunit"; />
						</div>
						<div style="float:left;width:100px;padding-left:100px;">&nbsp;</div>
						<div style="float:left;"><img src="'.$base_url.'/themes/theme2010/images/gi_online_volunteer_unit.jpg"/>
						</div>
					</div>
			  </div>
			  ';

	$sFooter = '
	</div><div style="height:50px;">&nbsp;</div>
</div></body></html>';

	return $sHeader.$sOutput.$sFooter;
}

function kickapps_offlinevolunteerunit(){
 global $user;

	$sHeader = drupal_eval(load_kickapps_template('page-team-volunteer'));

	$sOutput = '<div><center><h3>Offline Volunteer Unit</h3></center></div>';

	$sOutput .= '<div style="background-color:#ffffff;">
						<div align="center">
						<img src="'.$base_url.'/themes/theme2010/images/gi_offline_volunteer_unit_big.jpg" />
						</div>
						<div style="padding-top:12px;padding-left:12px;width:95%;">
						<b>Offline Volunteering Opportunites</b><br/>
						There are several opportunites available to volunteers who wish to provide direct supprt to the Hopefuls
						through the Hope Cybraries located in the elementary schools.
						<br/><br/>
						To learn more about the specific volunteering opportunites you go the the "Get Involved" section by
						clicking <a href="'.$base_url.'/mystudies/getinvolved/selectcybrarian">here</a><br/><br/>
						<b>Volunteer Unit Organization</b><br/>
						The Offline Volunteer teams are formed into units that are similar in structure to the Hopefuls team
						organization. The basic building block unit of the Volunteer Corps is the team. The volunteer teams are
						organized by city and school. Each school has a number of teams dependent upon the size of the school
						that they need to support.<br/><br/>
						Each school volunteeer team is manned by 12 volunteers. The teams are part of a unit called the "Volunteer Troop."
						There are up to four teams per troop and they are listed as the Red - Team, Blue - Team, White - Team, and Gold - Team.
						If more than 4 teams are required to support a school then an additional troop is created.
						</div>
						<div style="padding-top:12px;padding-left:12px;width:95%;">';

				$sOutput .= '<div style="width:900px;">'._volunteer_cybrarian_heirarchy(true).'</div>';

				$sOutput .= '</div>
						<div style="clear:both;padding-top:12px;padding-left:12px;width:100%;">
						Before you can join a team you must first enroll as an Offline Volunteer. To enroll just click on this
						"<a href="'.$base_url.'/mystudies/getinvolved/selectcybrarian">Get Involved</a>" link.<br/><br/>';

						$checkActivate = db_result(db_query("SELECT count(uid) as count FROM cybrarian_optin where uid = '{$user->uid}' AND activate = 1"));
						$disable = $checkActivate > 0 ? 'style="cursor:pointer"' : 'style="background: none repeat scroll 0 0 #e5e5e5;border: 1px solid #CCCCCC;color: #161616;margin: 0 0 12px;padding: 4px;"';
						$redirect = $checkActivate > 0 ? 'onclick=window.location='."'/community/volunteerteamdashboard';" : '';

				$sOutput .= '<input type="button" id="gotomyteam" name="gotomyteam" value="Go to My Team" '.$disable.' '.$redirect.'>';

				$sOutput .= '</div>
					</div>
				</div>
			  ';

	$sFooter = '
	</div><div style="height:50px;">&nbsp;</div>
</div></body></html>';

	return $sHeader.$sOutput.$sFooter;
}

function kickapps_volunteerteamdashboard(){
	global $user;

    $theme_imgpath = $base_url.'/themes/theme2010/images/';
	$sHeader = drupal_eval(load_kickapps_template('page-team-volunteer'));

	$sOutput .= '<div style="background-color:#ffffff;">
					'; // start

	$sOutput .= '<div style="background-color:#ffffff;" align="center">';

	$sqlMemberDetails = "SELECT B.kickappsteam_id, B.team_name, C.troop_id, C.troop_name, D.wing_id, D.wing_name, E.group_id, E.group_name
						FROM drupal.hope_teamusers A
						LEFT JOIN drupal.hope_team B ON B.kickappsteam_id = A.team_id
						LEFT JOIN drupal.hope_troop C ON C.troop_id = B.troop_id
						LEFT JOIN drupal.hope_wing D ON D.wing_id = C.wing_id
						LEFT JOIN drupal.hope_group E ON E.group_id = D.group_id
						WHERE A.uid = %d";

	$oDetailsResult = db_query($sqlMemberDetails, $user->uid);
	$oDetails = db_fetch_object($oDetailsResult);
	mysqli_free_result($oDetailsResult);
	$kickappsteam_id = $oDetails->kickappsteam_id;
	$team_name = $oDetails->team_name;
	$troop_id = $oDetails->troop_id;
	$troop_name = $oDetails->troop_name;
	$wing_id = $oDetails->wing_id;
	$wing_name = $oDetails->wing_name;
	$group_id = $oDetails->group_id;
	$group_name = $oDetails->group_name;
	$arr_colors = array('red', 'white','blue' ,'gold');

	$sOutput .= '<div style="width:200px;height:50px;"><ul><b style="font-size:18px;"><u>My Team</u></b></ul></div>';


	$sOutput .= '<div style="float:left;width:280px;height:70px;background-color:yellow;border:1px solid #b3b3b3;">
						Click the city and school in the dropdown box to see the existing hopeful units.<br/>
						<select id="Selectbycityteams" onchange="teamsselectbyschools_volunteer(this.value);">
						<option value="">Click City -></option>
						<option value="">->Makati</option>
						<option value="Jose Magsaysay Elementary School">--->Jose Magsaysay Elementary School</option>
						<option value="Francisco Benitez Elementary School">--->Francisco Benitez Elementary School</option>
						<option value="Maximo Estrella Elementary School" selected>--->Maximo Estrella Elementary School</option>
						</select>
				</div>
				<div style="float:left;width:30px;">&nbsp;</div>
				<div style="float:left;width:250px;height:70px;background-color:#1ef102;" id="group_name_teams"><b>'.$group_name.'</b><br/> Volunteer Organization</div>';

	$sOutput .= '
				<div id="coming_soonmsg" style="clear:both;display:none;height:200px;padding-top:80px;"><span style="color:red;"><b>Coming Soon..</b></span></div>
				<div id="heirarchy_menu" style="padding-left:50px;">';

	$sOutput .= '<div style="clear:both;"><img src="'.$theme_imgpath.'z_vline1.gif" /><img src="'.$theme_imgpath.'z_vline2.gif" /><img src="'.$theme_imgpath.'z_vline3.png" /><img src="'.$theme_imgpath.'z_vline4.gif" /></div>';

	$sOutput .= '<div align="center" style="padding-left:150px;">';
	$sqlTroop = "SELECT A.troop_id, A.troop_name
				FROM hope_troop A
				WHERE A.wing_id = %d";

	//$oTroopResult = db_query($sqlTroop, $wing_id);
	$oTroopResult = db_query($sqlTroop, 9);

	$coltroop = 0;
	$linetroop = '';
	while ($oTroop = db_fetch_object($oTroopResult)){
	$troopname = $oTroop->troop_name;
	$arr_troopname = explode(' ', $troopname);
	$troopcolor = strtolower($arr_troopname[0]);
	$troopcolorfont = $troopcolor == 'blue' ? 'white': 'black';

	if($oTroop->troop_id == $troop_id){
	$linetroop = $coltroop + 1;
	$sOutput .= '<div style="border:2px solid #1ef102;float:left;width:100px;height:50px;color:'.$troopcolorfont.';background-color:'.$troopcolor.';"><a href="javascript:void(0);" onclick="change_troopteams_volunteer2(\''.$oTroop->troop_id.'\',\''.'troop'.'\',\''.$linetroop.'\');" ><b style="color:'.$troopcolorfont.';">'.$oTroop->troop_name.'</b></a><br/>'.calculateTeam('troop',$oTroop->troop_id).' Member(s)</div><div style="float:left;width:10px;">&nbsp;</div>';
	} else{
	$comtroop = $coltroop + 1;
	$sOutput .= '<div style="border:1px solid #b3b3b3;float:left;width:100px;height:50px;color:'.$troopcolorfont.';background-color:'.$troopcolor.';"><a href="javascript:void(0);" onclick="change_troopteams_volunteer2(\''.$oTroop->troop_id.'\',\''.'troop'.'\',\''.$comtroop.'\');" ><b style="color:'.$troopcolorfont.';">'.$oTroop->troop_name.'</b></a><br/>'.calculateTeam('troop',$oTroop->troop_id).' Member(s)</div><div style="float:left;width:10px;">&nbsp;</div>';
	}
	$arr_troopname = '';
	$coltroop++;
	}
	mysqli_free_result($oTroopResult);
	$sOutput .= '</div>';

	if(isset($_GET['teamid'])){
	$sOutput .= '<script>
						change_troopteams_volunteer2("'.$_GET["teamid"].'", "team", "1");
					</script>';
	}

	$sOutput .= '<div style="clear:both;" id="teams_lines">
					<div><img src="'.$theme_imgpath.'z_level3line'.$linetroop.'.gif" /></div>
					<div><img src="'.$theme_imgpath.'z_level3line.png" /></div>
				</div>';

	$sOutput .= '<div id="teams_div"><div align="center" style="padding-left:130px;">';

	$sqlTeam = "SELECT A.kickappsteam_id, A.team_name, A.team_color, A.team_type, A.troop_id
					FROM hope_team A
					WHERE troop_id = %d";
	//$oTeamResult = db_query($sqlTeam, $troop_id);
	$oTeamResult = db_query($sqlTeam, 12);

	$colteam = 0;
	$lineteam = '';
	while ($oTeam = db_fetch_object($oTeamResult)){
	$arr_teamname = explode(' ', $oTeam->team_name);
	$teamcolor = strtolower($arr_teamname[0]);
	$teamcolorfont = $teamcolor == 'blue' ? 'white': 'black';
		if($oTeam->kickappsteam_id == $kickappsteam_id){
			$sOutput .= '<div style="border:2px solid #1ef102;float:left;width:100px;height:60px;color:'.$teamcolorfont.';background-color:'.$teamcolor.';"><a href="/community/volunteerteamdashboard?teamid='.$oTeam->kickappsteam_id.'"><b style="color:'.$teamcolorfont.';">'.$oTeam->team_name.'</b></a><br/>'.calculateTeam('team',$oTeam->kickappsteam_id).' Member(s)<br/></div><div style="float:left;width:10px;">&nbsp;</div>';
			$lineteam = $colteam;
		} else{
			$sOutput .= '<div style="border:1px solid #b3b3b3;float:left;width:100px;height:60px;color:'.$teamcolorfont.';background-color:'.$teamcolor.';"><a href="/community/volunteerteamdashboard?teamid='.$oTeam->kickappsteam_id.'"><b style="color:'.$teamcolorfont.';">'.$oTeam->team_name.'</b></a><br/>'.calculateTeam('team',$oTeam->kickappsteam_id).' Member(s)</div><div style="float:left;width:10px;">&nbsp;</div>';
		}
	$colteam++;
	}
	mysqli_free_result($oTeamResult);

	$sOutput .= '</div>';

	$sOutput .= '<div align="center" style="padding-left:130px;clear:both;">';
	$colyourteam = 0;
	while($colyourteam <= 4){
		if($colyourteam == $lineteam){
			$sOutput .= '<div style="float:left;width:100px;height:60px;">
							<img src="'.$theme_imgpath.'balloon_thisisyourteam.gif" />
						</div>
						<div style="float:left;width:10px;">
							&nbsp;
						</div>';
		} else{
			$sOutput .= '<div style="float:left;width:100px;height:60px;">
							&nbsp;
						</div>
						<div style="float:left;width:10px;">
							&nbsp;
						</div>';
		}
	$colyourteam++;
	}
	$sOutput .= '</div>
				</div><!--end teamdiv-->';

	$sOutput .= '<div style="clear:both;">&nbsp;</div>';

	$sOutput .= '</div>';
	$sOutput .= '</div>';

	if(isset($_GET['teamid'])){
	$kickappsteam_id = $_GET['teamid'];
	}

	$sOutput .= '<div style="padding-left:15px;"><div style="width:700px;border:1px solid #b3b3b3;"><div style="background-color:#cecece;margin: 0; height:30px;">&nbsp;<b>Announcement and News</b></div>
															<div class="jboxbody">
																<div class="jboxcontent">
																	<table style="background-color:#ffffff;" width="100%" height="200" border="0" cellspacing="0" cellpadding="0">
																		<tr>
																			<td width="350" valign="top" style="padding-top:5px;">';

									$sOutput .= '<div style="width: 600px;height:198px;overflow: auto;padding:8px;">';

									$sqlAnnounce = "SELECT teamnews_id, team_id, announce_text, announce_date
													FROM hope_team_news
													WHERE team_id = %d
													ORDER BY teamnews_id DESC
													";

										$oAnnounceResult = db_query($sqlAnnounce, $kickappsteam_id);

										$sOutput .= '';
										$Annoucnecount = 0;
										while ($oAnnounce = db_fetch_object($oAnnounceResult)){
											$sOutput .= $oAnnounce->announce_text.' <span style="font-size:10px;"><b>'.date("F j, Y, g:i a", $oAnnounce->announce_date).'</b></span><br/><br/>';
										$Annoucnecount++;
										}
										mysqli_free_result($oAnnounceResult);
										if($Annoucnecount == 0){
											$sOutput .= "There are no message post yet.";
										}

										$sOutput .= '</div>';


															$sOutput .= '</td>
																		</tr>
																	</table>
																</div>
															</div></div></div><div>&nbsp;</div>';

	$sOutput .= '<link rel="stylesheet" type="text/css" href="'.$base_url.'/themes/theme2010/style.css" />';

	$sqlSelectedTeamDetails = "SELECT B.kickappsteam_id, B.team_name, C.troop_id, C.troop_name, D.wing_id, D.wing_name, E.group_id, E.group_name
					    FROM drupal.hope_team B
						LEFT JOIN drupal.hope_troop C ON C.troop_id = B.troop_id
						LEFT JOIN drupal.hope_wing D ON D.wing_id = C.wing_id
						LEFT JOIN drupal.hope_group E ON E.group_id = D.group_id
						WHERE B.kickappsteam_id = '{$kickappsteam_id}'";

	$oSelectedTeamResult = db_query($sqlSelectedTeamDetails);
	$oSelected = db_fetch_object($oSelectedTeamResult);
	mysqli_free_result($oSelectedTeamResult);
	$skickappsteam_id = $oSelected->kickappsteam_id;
	$steam_name = $oSelected->team_name;
	$arrsteam_name = explode(' ', $steam_name);
	$strteam_colr = strtolower($arrsteam_name[0]);
	$strteam_fontcolr = $strteam_colr == 'blue' ? 'white' : 'black';
	$stroop_id = $oSelected->troop_id;
	$stroop_name = $oSelected->troop_name;
	$swing_id = $oSelected->wing_id;
	$swing_name = $oSelected->wing_name;
	$sgroup_id = $oSelected->group_id;
	$sgroup_name = $oSelected->group_name;

	switch($strteam_colr){
	case 'red': $meetallbutton = 'meet_allredteamvolunteers.gif'; break;
	case 'blue': $meetallbutton = 'meet_allblueteamvolunteers.gif'; break;
	case 'white': $meetallbutton = 'meet_allwhiteteamvolunteers.gif'; break;
	case 'gold': $meetallbutton = 'meet_allgoldteamvolunteers.gif'; break;
	}

	$sOutput .= '<div style="padding-left:15px;"><div style="width:700px;border:1px solid #b3b3b3;"><div style="background-color:#cecece;margin: 0; height:30px;">&nbsp;<b>'.$steam_name.' > '.$stroop_name.' > '.$swing_name.' > '.$sgroup_name.' - <b id="incybrary_block_title">Welcome!</b></div>
															<div class="jboxbody">
																<div class="jboxcontent">
																	<table width="100%" border="0" cellspacing="0" cellpadding="0" class="meet_info">
																		<tr>
																			<td width="350" valign="top" style="padding-top:5px;">
																				<div style="float:left;"><div style="border:1px solid #b3b3b3;float:left;width:180px;height:50px;font-size:26px;padding-top:20px;background-color:'.$strteam_colr.';"><center><b style="color:'.$strteam_fontcolr.'">'.$steam_name.'</b></center></div></div>
																				<div style="float:left;">&nbsp;</div>
																				<div style="float:left;" style="font-size:12px;width:150px;"><b>'.$steam_name.'</b><br/><b style="font-size:12px;">Kindness Hours: <span id="kindnesstotaltext" style="font-size:12px;"></span></b> <br/> <b style="font-size:12px;">Team Members: <span id="teammemberstotaltext" style="font-size:12px;"></span></b></div>
																			</td>
																			<td style="padding-top:5px;">
																				<div style="float:left;"><img id="incybrary_avatar" src="" style="cursor:pointer;"/></div>
																				<div style="float:left;">&nbsp;</div>
																			    <div style="float:left;">
																				<div id="incybrary_hopeful_details"></div>
																				</div>
																			</td>
																		</tr>
																		<tr>
																			<td colspan="2"><hr style="padding-top:20px; width:100%" class="divider" /></td>
																		</tr>
																		<tr>
																			<td colspan="2">
																				<table width="100%" border="0" cellspacing="0" cellpadding="2" style="float: left;padding: 5px;text-align: center;">
																				  <tr>
																					<td style="width:160px;padding-left:5px;">
																						<a id="button_children_online_volunteer" href="javascript:void(0);"><img src="'.$theme_imgpath.'meet_inthecybrarynow.gif" border="0" /></a><br />
																						<a id="button_children_24_volunteer" href="javascript:void(0);"><img src="'.$theme_imgpath.'meet_inthelast24.gif" border="0" /></a><br />
																						<a id="button_children_all_volunteer" href="javascript:void(0);"><img src="'.$theme_imgpath.$meetallbutton.'" border="0" /></a><br />
																					</td>
																					<td align="center">
																						<div id="incybrary_hopeful_list"></div>
																					</td>
																				  </tr>
																				</table>
																			</td>
																		</tr>
																		<tr>
																			<td colspan="2"><hr style="width:100%" class="divider" /></td>
																		</tr>
																		<tr>
																			<td colspan="2" align="right" class="pager">
																				<!--Pages : <a href="#">1</a> | <a href="#">2</a> | <a href="#">3</a> | -->
																				<div id="incybrary_hopeful_nav"></div>
																				<input type="hidden" id="teamid" name="teamid" value="'.$kickappsteam_id.'" />
																				<!--incybrary_hopeful_nav-->
																			</td>
																		</tr>
																	</table>
																</div>
															</div></div></div>';

	$sOutput .= '</div>'; // end

	$sFooter .= '<iframe id="communityiframe" scrolling="yes" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0" style="overflow-x: hidden;overflow-y: hidden;overflow:hidden; width:726px; height: 1200px;" src="http://affiliate.kickapps.com/_Hope-Team/group/'.$kickappsteam_id.'/158175.html?css=kickapps_theme2010&invite=yes"></iframe>';
	return $sHeader.$sOutput.$sFooter;
}

function kickapps_teams(){
	global $user;

	$sHeader = drupal_eval(load_kickapps_template('page-team-hopefuls'));
	$sOutput .= '<div style="background-color:#386631;">
					<div id="request_message_div" style="display:none;">&nbsp;</div>
					<center><br/><br/>
					<img src="'.$base_url.'/themes/theme2010/images/gi_community_building_teams.jpg" />
					</center>
					<div align="center" style="padding-bottom:50px;color:white;">
						Text Box
					</div>';

	$sqlKickappsIDExist = "SELECT team_id FROM hope_teamusers WHERE uid = %d";
	$oKickappsID = db_result(db_query($sqlKickappsIDExist, $user->uid));

	$sqlUserExist = "SELECT COUNT(team_userid) as count FROM hope_teamusers WHERE uid = %d";
	$oUserExistResult = db_result(db_query($sqlUserExist, $user->uid));

	if($oUserExistResult > 0){
	$sOutput .= '<div align="center" style="width:100%;height:100px;background-color:#386631;">
					<center><input type="button" class="ka_button" value="View My Team" onclick="window.location='."'http://www.hopecybary.org/community/manageteam';".'"/></center>
				</div>';
	} else{
	$sOutput .= '<div align="center" style="width:100%;height:100px;background-color:#386631;">
						<center><input type="button" id="join_team_button" name="join_team_button" class="ka_button" value="Join Team" /></center>
				</div>';
	}

	$sOutput .= '</div>';

	$sFooter = '
	</div><div style="height:50px;">&nbsp;</div>
</div>
<iframe id="communityiframe" style="visibility:hidden;" src="http://affiliate.kickapps.com/_Hope-Team/group/'.$oKickappsID.'/158175.html?css=kickapps_theme2010&invite=yes"></iframe>
</body></html>';

	//mysqli_free_result($oKickappsID);
	//mysqli_free_result($oUserExistResult);
	return $sHeader.$sOutput.$sFooter;
}

function kickapps_manage_team(){
	global $user;

    $theme_imgpath = $base_url.'/themes/theme2010/images/';
	$sHeader = drupal_eval(load_kickapps_template('page-team-hopefuls'));

	$sOutput .= '<div style="background-color:#17450f;">
					'; // start

	$sOutput .= '<div style="background-color:#17450f;" align="center">';

	$sqlMemberDetails = "SELECT B.kickappsteam_id, B.team_name, C.troop_id, C.troop_name, D.wing_id, D.wing_name, E.group_id, E.group_name
						FROM drupal.hope_teamusers A
						LEFT JOIN drupal.hope_team B ON B.kickappsteam_id = A.team_id
						LEFT JOIN drupal.hope_troop C ON C.troop_id = B.troop_id
						LEFT JOIN drupal.hope_wing D ON D.wing_id = C.wing_id
						LEFT JOIN drupal.hope_group E ON E.group_id = D.group_id
						WHERE A.uid = %d";

	$oDetailsResult = db_query($sqlMemberDetails, $user->uid);
	$oDetails = db_fetch_object($oDetailsResult);
	mysqli_free_result($oDetailsResult);
	$kickappsteam_id = $oDetails->kickappsteam_id;
	$team_name = $oDetails->team_name;
	$troop_id = $oDetails->troop_id;
	$troop_name = $oDetails->troop_name;
	$wing_id = $oDetails->wing_id;
	$wing_name = $oDetails->wing_name;
	$group_id = $oDetails->group_id;
	$group_name = $oDetails->group_name;
	$arr_colors = array('red', 'white','blue' ,'gold');

	$sOutput .= '<div style="width:200px;height:50px;"><ul><b style="font-size:18px;color:white;"><u>My Team</u></b></ul></div>';

	$sOutput .= '<div><div style="float:left;width:20px;">&nbsp;</div>
				<div style="float:left;width:280px;height:70px;background-color:yellow;border:1px solid #b3b3b3;">
						Click the city and school in the dropdown box to see the existing hopeful units.<br/>
						<select id="Selectbycityteams" onchange="teamsselectbyschools(this.value);">
						<option value="">Click City -></option>
						<option value="">->Makati</option>
						<option value="Jose Magsaysay Elementary School">--->Jose Magsaysay Elementary School</option>
						<option value="Francisco Benitez Elementary School">--->Francisco Benitez Elementary School</option>
						<option value="Maximo Estrella Elementary School" selected>--->Maximo Estrella Elementary School</option>
						</select>
				</div>
				<div style="float:left;width:30px;">&nbsp;</div>
				<div style="float:left;width:250px;height:70px;background-color:#1ef102;" id="group_name_teams"><b>'.$group_name.'</b><br/> Community Building Teams</div>
				</div>';

	$sOutput .= '
				<div id="coming_soonmsg" style="width:700px;clear:both;display:none;height:200px;padding-top:80px;"><span style="color:red;"><b>Coming Soon..</b></span></div>
				<div id="heirarchy_menu" style="background-color:white;width:700px;">
					<div style="clear:both;"><img src="'.$theme_imgpath.'z_level1line.png" /></div>';

	$sOutput .= '<div style="padding-right:200px;"><div style="width:100px;height:50px;background-color:red;">'.$wing_name.'<br/>'.calculateTeam('wing',$wing_id).' Member(s)</div></div>';

	$sOutput .= '<div style="clear:both;"><img src="'.$theme_imgpath.'z_line1.gif" /><img src="'.$theme_imgpath.'z_line2.gif" /><img src="'.$theme_imgpath.'z_line3.png" /><img src="'.$theme_imgpath.'z_line4.gif" /></div>';

	$sOutput .= '<div align="center" style="padding-left:150px;">';
	$sqlTroop = "SELECT A.troop_id, A.troop_name
				FROM hope_troop A
				WHERE A.wing_id = %d";

	$oTroopResult = db_query($sqlTroop, $wing_id);
	$coltroop = 0;
	$linetroop = '';
	while ($oTroop = db_fetch_object($oTroopResult)){
	if($oTroop->troop_id == $troop_id){
	$linetroop = $coltroop + 1;
	$arr_troopname = explode(' ',$oTroop->troop_name);
	$troopcolor = strtolower($arr_troopname[0]);
	$troopcolorfont = $troopcolor == 'blue' ? 'white': 'black';

	$sOutput .= '<div style="border:2px solid #1ef102;float:left;width:100px;height:50px;color:'.$troopcolorfont.';background-color:'.$troopcolor.';"><a href="javascript:void(0);" onclick="change_troopteams(\''.$oTroop->troop_id.'\',\''.'troop'.'\',\''.$linetroop.'\');" ><b style="color:'.$teamcolorfont.';">'.$oTroop->troop_name.'</b></a><br/>'.calculateTeam('troop',$oTroop->troop_id).' Member(s)</div><div style="float:left;width:10px;">&nbsp;</div>';
	} else{
	$comtroop = $coltroop + 1;
	$sOutput .= '<div style="border:1px solid #b3b3b3;float:left;width:100px;height:50px;color:'.$troopcolorfont.';background-color:'.$troopcolor.';"><a href="javascript:void(0);" onclick="change_troopteams(\''.$oTroop->troop_id.'\',\''.'troop'.'\',\''.$comtroop.'\');" ><b style="color:'.$teamcolorfont.';">'.$oTroop->troop_name.'</b></a><br/>'.calculateTeam('troop',$oTroop->troop_id).' Member(s)</div><div style="float:left;width:10px;">&nbsp;</div>';
	}
	$coltroop++;
	}
	mysqli_free_result($oTroopResult);
	$sOutput .= '</div>';

	if(isset($_GET['teamid'])){
	$sOutput .= '<script>
						change_troopteams("'.$_GET["teamid"].'", "team", "1");
					</script>';
	}

	$sOutput .= '<div style="clear:both;" id="teams_lines">
					<div><img src="'.$theme_imgpath.'z_level3line'.$linetroop.'.gif" /></div>
					<div><img src="'.$theme_imgpath.'z_level3line.png" /></div>
				</div>';

	$sOutput .= '<div id="teams_div"><div align="center" style="padding-left:130px;">';

	$sqlTeam = "SELECT A.kickappsteam_id, A.team_name, A.team_color, A.team_type, A.troop_id
					FROM hope_team A
					WHERE troop_id = %d";
	$oTeamResult = db_query($sqlTeam, $troop_id);
	$colteam = 0;
	$lineteam = '';
	while ($oTeam = db_fetch_object($oTeamResult)){
	$arr_teamname = explode(' ',$oTeam->team_name);
	$teamcolor = strtolower($arr_teamname[0]);
	$teamcolorfont = $teamcolor == 'blue' ? 'white': 'black';
		if($oTeam->kickappsteam_id == $kickappsteam_id){
			$sOutput .= '<div style="border:2px solid #1ef102;float:left;width:100px;height:60px;color:'.$teamcolorfont.';background-color:'.$teamcolor.';"><a href="/community/manageteam?teamid='.$oTeam->kickappsteam_id.'"><b style="color:'.$teamcolorfont.';">'.$oTeam->team_name.'</b></a><br/>'.calculateTeam('team',$oTeam->kickappsteam_id).' Member(s)<br/></div><div style="float:left;width:10px;">&nbsp;</div>';
			$lineteam = $colteam;
		} else{
			$sOutput .= '<div style="border:1px solid #b3b3b3;float:left;width:100px;height:60px;color:'.$teamcolorfont.';background-color:'.$teamcolor.';"><a href="/community/manageteam?teamid='.$oTeam->kickappsteam_id.'"><b style="color:'.$teamcolorfont.';">'.$oTeam->team_name.'</b></a><br/>'.calculateTeam('team',$oTeam->kickappsteam_id).' Member(s)</div><div style="float:left;width:10px;">&nbsp;</div>';
		}
	$colteam++;
	}
	mysqli_free_result($oTeamResult);

	$sOutput .= '</div>';

	$sOutput .= '<div align="center" style="padding-left:130px;clear:both;">';
	$colyourteam = 0;
	while($colyourteam <= 4){
		if($colyourteam == $lineteam){
			$sOutput .= '<div style="float:left;width:100px;height:60px;">
							<img src="'.$theme_imgpath.'balloon_thisisyourteam.gif" />
						</div>
						<div style="float:left;width:10px;">
							&nbsp;
						</div>';
		} else{
			$sOutput .= '<div style="float:left;width:100px;height:60px;">
							&nbsp;
						</div>
						<div style="float:left;width:10px;">
							&nbsp;
						</div>';
		}
	$colyourteam++;
	}
	$sOutput .= '</div>
				</div><!--end teamdiv-->';

	$sOutput .= '<div style="clear:both;">&nbsp;</div>';

	$sOutput .= '</div>';
	$sOutput .= '</div>
				<div style="height:10px;background-color:#17450f;">&nbsp;</div>
				';

	if(isset($_GET['teamid'])){
	$kickappsteam_id = $_GET['teamid'];
	}

	$sOutput .= '<div style="padding-left:15px;"><div style="width:700px;border:1px solid #b3b3b3;"><div style="background-color:#386631;color:white;margin: 0; height:30px;">&nbsp;<b>Announcement and News</b></div>
															<div class="jboxbody">
																<div class="jboxcontent">
																	<table style="background-color:#ffffff;" width="100%" height="200" border="0" cellspacing="0" cellpadding="0">
																		<tr>
																			<td width="350" valign="top" style="padding-top:5px;">';

									$sOutput .= '<div style="width: 600px;height:198px;overflow: auto;padding:8px;">';

									$sqlAnnounce = "SELECT teamnews_id, team_id, announce_text, announce_date
													FROM hope_team_news
													WHERE team_id = %d
													ORDER BY teamnews_id DESC
													";

										$oAnnounceResult = db_query($sqlAnnounce, $kickappsteam_id);

										$sOutput .= '';
										$Annoucnecount = 0;
										while ($oAnnounce = db_fetch_object($oAnnounceResult)){
											$sOutput .= $oAnnounce->announce_text.' <span style="font-size:10px;"><b>'.date("F j, Y, g:i a", $oAnnounce->announce_date).'</b></span><br/><br/>';
										$Annoucnecount++;
										}
										if($Annoucnecount == 0){
											$sOutput .= "There are no message post yet.";
										}
										mysqli_free_result($oAnnounceResult);

										$sOutput .= '</div>';


															$sOutput .= '</td>
																		</tr>
																	</table>
																</div>
															</div></div></div><div>&nbsp;</div>';

	$sOutput .= '<link rel="stylesheet" type="text/css" href="'.$base_url.'/themes/theme2010/style.css" />';

	$sqlSelectedTeamDetails = "SELECT B.kickappsteam_id, B.team_name, C.troop_id, C.troop_name, D.wing_id, D.wing_name, E.group_id, E.group_name
					    FROM drupal.hope_team B
						LEFT JOIN drupal.hope_troop C ON C.troop_id = B.troop_id
						LEFT JOIN drupal.hope_wing D ON D.wing_id = C.wing_id
						LEFT JOIN drupal.hope_group E ON E.group_id = D.group_id
						WHERE B.kickappsteam_id = '{$kickappsteam_id}'";

	$oSelectedTeamResult = db_query($sqlSelectedTeamDetails);
	$oSelected = db_fetch_object($oSelectedTeamResult);
	mysqli_free_result($oSelectedTeamResult);
	$skickappsteam_id = $oSelected->kickappsteam_id;
	$steam_name = $oSelected->team_name;
	$arrsteam_name = explode(' ', $steam_name);
	$strteam_colr = strtolower($arrsteam_name[0]);
	$strteam_fontcolr = $strteam_colr == 'blue' ? 'white' : 'black';
	$stroop_id = $oSelected->troop_id;
	$stroop_name = $oSelected->troop_name;
	$swing_id = $oSelected->wing_id;
	$swing_name = $oSelected->wing_name;
	$sgroup_id = $oSelected->group_id;
	$sgroup_name = $oSelected->group_name;

	switch($strteam_colr){
	case 'red': $meetallbutton = 'meet_allredteamhopefuls.gif'; break;
	case 'blue': $meetallbutton = 'meet_allblueteamhopefuls.gif'; break;
	case 'white': $meetallbutton = 'meet_allwhiteteamhopefuls.gif'; break;
	case 'gold': $meetallbutton = 'meet_allgoldteamhopefuls.gif'; break;
	}

	$sOutput .= '<div style="padding-left:15px;"><div style="background-color:white;width:700px;border:1px solid #b3b3b3;"><div style="background-color:#386631;margin: 0; height:30px;color:white;">&nbsp;<b>'.$steam_name.' > '.$stroop_name.' > '.$swing_name.' > '.$sgroup_name.' - <b id="incybrary_block_title">Welcome!</b></div>
															<div class="jboxbody">
																<div class="jboxcontent">
																	<table width="100%" border="0" cellspacing="0" cellpadding="0" class="meet_info">
																		<tr>
																			<td width="350" valign="top" style="padding-top:5px;">
																				<div style="float:left;"><div style="border:1px solid #b3b3b3;float:left;width:180px;height:50px;font-size:26px;padding-top:20px;background-color:'.$strteam_colr.';"><center><b style="color:'.$strteam_fontcolr.'">'.$steam_name.'</b></center></div></div>
																				<div style="float:left;">&nbsp;</div>
																				<div style="float:left;" style="font-size:12px;"><b>'.$steam_name.'</b><br/><b style="font-size:12px;">2Kindness Hours:</b><label id="kindnesstotaltext" style="font-size:12px;"></label><b style="font-size:12px;">Knowledge Hours:</b><label id="knowledgetotaltext" style="font-size:12px;"></label></div>
																			</td>
																			<td style="padding-top:5px;">
																				<div style="float:left;"><img id="incybrary_avatar" src=""/></div>
																				<div style="float:left;">&nbsp;</div>
																			    <div style="float:left;">
																				<div id="incybrary_hopeful_details"></div>
																				</div>
																			</td>
																		</tr>
																		<tr>
																			<td colspan="2"><hr style="padding-top:20px; width:100%" class="divider" /></td>
																		</tr>
																		<tr>
																			<td colspan="2">
																				<table width="100%" border="0" cellspacing="0" cellpadding="2" style="float: left;padding: 5px;text-align: center;">
																				  <tr>
																					<td style="width:160px;padding-left:5px;">
																						<a id="button_children_online" href="javascript:void(0);"><img src="'.$theme_imgpath.'meet_inthecybrarynow.gif" border="0" /></a><br />
																						<a id="button_children_24" href="javascript:void(0);"><img src="'.$theme_imgpath.'meet_inthelast24.gif" border="0" /></a><br />
																						<a id="button_children_all" href="javascript:void(0);"><img src="'.$theme_imgpath.$meetallbutton.'" border="0" /></a><br />
																					</td>
																					<td align="center">
																						<div id="incybrary_hopeful_list"></div>
																					</td>
																				  </tr>
																				</table>
																			</td>
																		</tr>
																		<tr>
																			<td colspan="2"><hr style="width:100%" class="divider" /></td>
																		</tr>
																		<tr>
																			<td colspan="2" align="right" class="pager">
																				<!--Pages : <a href="#">1</a> | <a href="#">2</a> | <a href="#">3</a> | -->
																				<div id="incybrary_hopeful_nav"></div>
																				<input type="hidden" id="teamid" name="teamid" value="'.$kickappsteam_id.'" />
																				<!--incybrary_hopeful_nav-->
																			</td>
																		</tr>
																	</table>
																</div>
															</div></div></div>';

	$sOutput .= '</div>'; // end

	$sFooter .= '<div style="height:10px;background-color:#17450f;">&nbsp;</div><iframe scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0" style="overflow-x: hidden;overflow-y: hidden;overflow:hidden; width:726px; height: 1200px;" src="http://affiliate.kickapps.com/_Hope-Team/group/'.$kickappsteam_id.'/158175.html?invite=yes"></iframe>';
	echo $sHeader.$sOutput.$sFooter.memory_get_usage();
}

// function calculateTeam($type, $id){

// 	switch($type){
// 	case 'team':
// 	$sqlSelectedTeamDetails = "SELECT count(A.team_userid) as count
// 						FROM drupal.hope_teamusers A
// 						LEFT JOIN drupal.hope_team B ON B.kickappsteam_id = A.team_id
// 						LEFT JOIN drupal.hope_troop C ON C.troop_id = B.troop_id
// 						LEFT JOIN drupal.hope_wing D ON D.wing_id = C.wing_id
// 						LEFT JOIN drupal.hope_group E ON E.group_id = D.group_id
// 						WHERE A.team_id = %d";

// 	$oSelectedTeamResult = db_query($sqlSelectedTeamDetails, $id);
// 	$res = db_fetch_object($oSelectedTeamResult);
// 	mysqli_free_result($oSelectedTeamResult);
// 	break;
// 	case 'troop':
// 	$sqlSelectedTeamDetails = "SELECT count(A.team_userid) as count
// 								FROM drupal.hope_teamusers A
// 								LEFT JOIN drupal.hope_team B ON B.kickappsteam_id = A.team_id
// 								LEFT JOIN drupal.hope_troop C ON C.troop_id = B.troop_id
// 								WHERE C.troop_id = %d";

// 	$oSelectedTeamResult = db_query($sqlSelectedTeamDetails, $id);
// 	$res = db_fetch_object($oSelectedTeamResult);
// 	mysqli_free_result($oSelectedTeamResult);
// 	break;
// 	case 'wing':
// 	$sqlSelectedTeamDetails = "SELECT count(A.team_userid) as count
// 								FROM drupal.hope_teamusers A
// 								LEFT JOIN drupal.hope_team B ON B.kickappsteam_id = A.team_id
// 								LEFT JOIN drupal.hope_troop C ON C.troop_id = B.troop_id
// 								LEFT JOIN drupal.hope_wing D ON D.wing_id = C.wing_id
// 								WHERE D.wing_id = %d";

// 	$oSelectedTeamResult = db_query($sqlSelectedTeamDetails, $id);
// 	$res = db_fetch_object($oSelectedTeamResult);
// 	mysqli_free_result($oSelectedTeamResult);
// 	break;
// 	}

// 	return $res->count;
// }

function load_kickapps_template($sPage){
	ob_start();
	include drupal_get_path('module', 'kickapps') . '/templates/' . $sPage . '.tpl.php';
	$sOutput = ob_get_contents();
	ob_end_clean();
	return $sOutput;
}

function kickapps_members($request = ""){
    //drupal_add_js(drupal_get_path("module", "kickapps")."/kickapps.js");

	//if (isset($request)){
	if ($request){
		foreach ($request as $sKey => $sData) {
			${$sKey} = $sData;
		}
	}

	$sBasePath = base_path();
	$iCount = 1;
	$iMaxCol = 4;
	$iMaxRec = $iMaxCol * 10;
	$aParam = array();

	if($_GET['css'] == 'kickapps_theme2010'){
	$sHeader = drupal_eval(load_kickapps_template('page-member-volunteer'));
    } else{
	$sHeader = drupal_eval(load_kickapps_template('page-member-hopefuls'));
	}

	$sHeader .= '
	<!--<div id="profile_Dialog" title="Profile" style="display:none;"><iframe id="hc_HopefulProfile1" style="position: abosolute;top: 0; left: 0;width:100%;height:95%;"></iframe></div>-->
	<div id="hc_HopefulProfileContainer" style="display:none; z-index:9000;" align="center">
					<div style="text-align:right; cursor:pointer; font-family:verdana; padding:5px 5px 5px 0; color:maroon; font-weight:bold; background-color:#F8F8F8;"><span id="hc_HopefulProfileContainerMaximize">[maximize]</span>&nbsp;<span id="hc_HopefulProfileContainerClose">[close this]</span></div>
					<iframe id="hc_HopefulProfile" src="" width="838" height="471" border="0"></iframe>
				</div>
	<form method="post" action="'.$sBasePath.str_replace("q=", "", $_SERVER["QUERY_STRING"]).'"><table>
				';
	$sFooter = '</table></form>
	</div>
</div></body></html>';

	$sOutput = '';
	$sUserType = '<option value="">Select User Group...</option><option value="">All</option>';

	$sqlUserType = "SELECT rid, `name` FROM role WHERE rid NOT IN (1, 10) ORDER BY `name`";
	$oUserTypeResult = db_query($sqlUserType);

	while ($oUserType = db_fetch_object($oUserTypeResult)){
		$iRoleId = $oUserType->rid;

		if (isset($kickapps_iUserTypeId)){
			$sCheckThis = ($kickapps_iUserTypeId == $iRoleId) ? 'selected="selected"':'';
		}else{
			$sCheckThis = '';
		}

		$sUserType .= '<option value="'.$iRoleId.'" '.$sCheckThis.'>'.$oUserType->name.'</option>';
	}
	mysqli_free_result($oUserTypeResult);

	if($_GET['css'] == 'kickapps_theme2010'){
	$sHeader .= '<tr>
					<td colspan="'.$iMaxCol.'" style="padding-bottom:20px;">
						<select id="kickapps_iUserTypeId" name="kickapps_iUserTypeId">'.$sUserType.'</select>&nbsp;
						<input type="submit" id="kickapps_btnFilter" name="kickapps_btnFilter" value="Filter"/>
						<div id="profile_Dialog_loader"></div>
					</td>
				</tr>';
	}

	$sqlPre1 = "SELECT A.uid, A.mail, A.name AS sUser, C.name AS sUserType, A.picture
				FROM users A
				INNER JOIN users_roles B ON B.uid = A.uid
				INNER JOIN role C ON C.rid = B.rid
				INNER JOIN profile_values D ON D.uid = A.uid
				%s GROUP BY A.uid";

	$sqlPre2 = "SELECT COUNT(A.uid)
				FROM users A
				INNER JOIN users_roles B ON B.uid = A.uid
				INNER JOIN role C ON C.rid = B.rid
				INNER JOIN profile_values D ON D.uid = A.uid
				%s";

	$sWhereClause = (isset($_REQUEST["kickapps_iUserTypeId"]) && $_REQUEST["kickapps_iUserTypeId"] != "") ? " WHERE C.rid = '".$_REQUEST["kickapps_iUserTypeId"]."' AND A.uid NOT IN (0, 1) AND D.value = 'Maximo Estrella Elementary School' and A.inactive = '3'":" WHERE C.rid = '9' AND A.uid NOT IN (0, 1) AND D.value = 'Maximo Estrella Elementary School' and A.inactive = '3'";
	$sOrderClause = " ORDER BY A.name";

	$sqlPre1 = sprintf($sqlPre1, $sWhereClause);
	$sqlPre2 = sprintf($sqlPre2, $sWhereClause);

	$oQueryResult = pager_query($sqlPre1.$sOrderClause, $iMaxRec, 0, $sqlPre2);
	$iMaxCol = 4;
	$iCount = 1;
	while ($oQuery = db_fetch_object($oQueryResult)){
		if ($iCount == 1) $sOutput .= '<tr>';
		if($oQuery->uid > 0){
		$sOutput .= '<td style="text-align:center; width:215px; heigh:315px; padding-bottom:10px;">
		               <div style="margin:2px; 2px; 2px; 2px;padding-top:12px; padding-bottom:12px;background-color: #FFFFFF !important; background-image: none; border: 1px solid #cdcdcd !important; color: #000000 !important; font-size: 12px;"">
						<div><img id="picture_'.$oQuery->uid.'" email="'.$oQuery->mail.'" src="'.$sBasePath.$oQuery->picture.'" style="cursor:pointer;" border="0" /></div>
						<div id="name_'.$oQuery->uid.'">'.$oQuery->sUser.'</div>
					   </div>
					</td>';
		}

		if ($iCount == $iMaxCol){
			$sOutput .= '</tr>';
			$iCount = 1;
		}else{
			$iCount++;
		}
	}
	mysqli_free_result($oQueryResult);

	while ($iCount < $iMaxCol){
		$sOutput .= '<td></td>';
		$iCount++;
	}

	if ($iCount == $iMaxCol) $sOutput .= '</tr>';

	//$sPagerHTML = ($sOutput != "") ? '<br/><br/>'.theme("pager", null, $iMaxRec):'';
	$sPagerHTML = ($sOutput != "") ? '<br/><br/>'.theme("pager", null, $iMaxRec):'';

	if($_GET['css'] == 'kickapps_theme2010'){
	return $sHeader.$sOutput.$sFooter.$sPagerHTML;
	} else{
	echo $sHeader.$sOutput.$sFooter.$sPagerHTML;
	}
	// end of members page
}

function kickapps_admin(){
	watchdog("KickApps", "Make admin");

	$form['kickapps_sitename'] = array(
		'#type' => 'textfield',
		'#title' => 'KickApps Site Name',
		'#default_value' => variable_get('kickapps_sitename',''),
		'#size' => 25,
		'#maxlength' => 256,
		'#description' => "The name of the site exactly as defined in the KickApps Affiliate site."
	);

	$form['kickapps_username'] = array(
		'#type' => 'textfield',
		'#title' => 'KickApps Username',
		'#default_value' => variable_get('kickapps_username', ''),
		'#size' => 25,
		'#maxlength' => 256,
		'#description' => "The username for the KickApps Affiliate Site."
	);

	$form['kickapps_email'] = array(
		'#type' => 'textfield',
		'#title' => 'KickApps Email',
		'#default_value' => variable_get('kickapps_email', ''),
		'#size' => 75,
		'#maxlength' => 256,
		'#description' => "The email address used in the KickAps Affiliate Site"
	);

	return system_settings_form($form);
}

/*
This function will create the SOAP request and send it to the KickApp server.
*/
function _kickapps_sign_in($user_obj, $save_to_session){
	$userid = $user_obj->uid;
	$affiliateUserName = variable_get('kickapps_username', '');
	$affiliateEmail = variable_get('kickapps_email', '');
	$affiliateSiteName = variable_get('kickapps_sitename', '');
	$requestType = "signInRegisterUser";

	# --BEGIN Get User Details
	$aProfile = _kickapps_get_profile($userid);

	$sFirstName = ucwords($aProfile["profile_first_name"]);
	$sLastName = ucwords($aProfile["profile_last_name"]);
	$sGender = substr($aProfile["profile_gender"], 0, 1);

	$aDOB = unserialize($aProfile["profile_dob"]);
	$dDOB = $aDOB["year"]."-".str_pad($aDOB["month"], 2, "0", STR_PAD_LEFT)."-".str_pad($aDOB["day"], 2, "0", STR_PAD_LEFT);
	$iAge = floor((time() - strtotime($dDOB)) / (60*60*24*365.2425));

	// Workaround so those who are younger than 13 years can be registered
	if ($iAge < 13) $dDOB = ($aDOB["year"] - 100)."-".str_pad($aDOB["month"], 2, "0", STR_PAD_LEFT)."-".str_pad($aDOB["day"], 2, "0", STR_PAD_LEFT);
	# --END Get User Details

	/* NOTE below if you are using DNS masking, you MUST replace affiliate.kickapps.com with
	your DNS masked URL e.g. community.yoursite.com */
	$kickapps_client = new SOAPClient("http://affiliate.kickapps.com/kickapps/soap/KaSoapSvc?WSDL");

	$kickapps_client->trace = 4;
	$auth->AffiliateUserName = $affiliateUserName;
	$auth->AffiliateEmail = $affiliateEmail;
	$doc = new DomDocument('1.0', 'UTF-8');
	$header_input = array('ns2:AffiliateUserName' => $affiliateUserName, 'ns2:AffiliateUserEmail' =>$affiliateEmail);
	$headerVar = new SoapVar($header_input, SOAP_ENC_OBJECT);
	$headert = new SoapHeader('http://schemas.kickapps.com/services/soap',	'AffiliateAuthenticationToken', $headerVar);
	$kickapps_client->__setSoapHeaders(array($headert));
	$nodeKassoRequest = $doc->createElementNS("http://schemas.kickapps.com/services/soap","KassoRequest");
	$nodeKassoRequest = $doc->appendChild($nodeKassoRequest);
	$requestName = $nodeKassoRequest->setAttribute("requestName", $requestType);

	/* dynamically replace this with the username of the member currently registering or logging in*/
	$userName = $user_obj->name;

	/* dynamically replace this with the email of the member currently registering */
	$email = $user_obj->mail;

	/* dynamically replace this with the first name of the member currently registering OPTIONAL */
	$firstName = $sFirstName;

	/* dynamically replace this with the last name of the member currently registering OPTIONAL */
	$lastName = $sLastName;

	/* build the request XML document */
	$nodeaffiliateUserName = $doc->createElement("Param");
	$newnodeaffiliateUserName = $nodeKassoRequest->appendChild($nodeaffiliateUserName);
	$paraNameAttr = $nodeaffiliateUserName->setAttribute("paramName", "affiliateUserName");
	$paramValue = $nodeaffiliateUserName->setAttribute("paramValue", $affiliateUserName);

	$nodeaffiliateEmail = $doc->createElement("Param");
	$newnodeaffiliateEmail = $nodeKassoRequest->appendChild($nodeaffiliateEmail);
	$paraNameAttr = $nodeaffiliateEmail->setAttribute("paramName", "affiliateEmail");
	$paramValue = $nodeaffiliateEmail->setAttribute("paramValue", $affiliateEmail);

	$nodeaffiliateSiteName = $doc->createElement("Param");
	$newnodeaffiliateSiteName = $nodeKassoRequest->appendChild($nodeaffiliateSiteName);
	$paraNameAttr = $nodeaffiliateSiteName->setAttribute("paramName", "affiliateSiteName");
	$paramValue = $nodeaffiliateSiteName->setAttribute("paramValue", $affiliateSiteName);

	$nodeuserName = $doc->createElement("Param");
	$newnodeuserName = $nodeKassoRequest->appendChild($nodeuserName);
	$paraNameAttr = $nodeuserName->setAttribute("paramName", "userName");
	$paramValue = $nodeuserName->setAttribute("paramValue", $userName);

	$nodeemail = $doc->createElement("Param");
	$newnodeemail = $nodeKassoRequest->appendChild($nodeemail);
	$paraNameAttr = $nodeemail->setAttribute("paramName", "email");
	$paramValue = $nodeemail->setAttribute("paramValue", $email);

	$nodeforce = $doc->createElement("Param");
	$newnodeemail = $nodeKassoRequest->appendChild($nodeforce);
	$paraNameAttr = $nodeforce->setAttribute("paramName", "forceEmailUpdate");
	$paramValue = $nodeforce->setAttribute("paramValue", "true");

	$nodebirthday = $doc->createElement("Param");
	$newnodebirthday = $nodeKassoRequest->appendChild($nodebirthday);
	$paraNameAttr = $nodebirthday->setAttribute("paramName", "birthday");
	$paramValue = $nodebirthday->setAttribute("paramValue", $dDOB);

	$nodefirstName = $doc->createElement("Param");
	$newnodefirstName = $nodeKassoRequest->appendChild($nodefirstName);
	$paraNameAttr = $nodefirstName->setAttribute("paramName", "firstName");
	$paramValue = $nodefirstName->setAttribute("paramValue", $firstName);

	$nodelastName = $doc->createElement("Param");
	$newnodelastName = $nodeKassoRequest->appendChild($nodelastName);
	$paraNameAttr = $newnodelastName->setAttribute("paramName", "lastName");
	$paramValue = $newnodelastName->setAttribute("paramValue", $lastName);

	$nodegender = $doc->createElement("Param");
	$newnodegender = $nodeKassoRequest->appendChild($nodegender);
	$paraNameAttr = $newnodegender->setAttribute("paramName", "gender");
	$paramValue = $newnodegender->setAttribute("paramValue", $sGender);

	$doc->appendChild($nodeKassoRequest);

	try {
		$result = $kickapps_client->processRequest($doc->saveXML());

		if ($save_to_session == 1){

			$dom_doc = new DOMDocument();
			$dom_doc->loadXML($result);
			$params = $dom_doc->getElementsByTagName("Param");

			$sessionParam = $params->item(1);
			$transactionParam = $params->item(2);
			$uidParam = $params->item(4);
			$cnameParam = $params->item(5);
			$userNameParam = $params->item(6);

			$st = $sessionParam->getAttribute('paramValue');
			$tid = $transactionParam->getAttribute('paramValue');
			$uid = $uidParam->getAttribute('paramValue');
			$cname = $cnameParam->getAttribute('paramValue');
			$userName = $userNameParam->getAttribute('paramValue');

			watchdog("KickApps", "st:".$st.", uid:".$uid.", tid:".$tid);

			$_SESSION['ka_st'] = $st;
			$_SESSION['ka_tid'] = $tid;
			$_SESSION['ka_uid'] = $uid;
			$_SESSION['ka_cname'] = $cname;
			$_SESSION['ka_user'] = $userName;
		}
	} catch(SOAPFault $soapex) {
		watchdog("KickApps Error", $soapex->getMessage()." Current age is ".$iAge.". DOB is ".$dDOB.".");
	}
}

function _kickapps_update_user($oUser){
/*
	$iUserId = $oUser->uid;
	$sAffUserName = variable_get('kickapps_username', '');
	$sAffUserEmail = variable_get('kickapps_email', '');
	$sAffSiteName = variable_get('kickapps_sitename', '');
	$sRequestType = "changeUserName";

	$sUserName = $oUser->name;
	$sEmail = $oUser->mail;

	# --BEGIN Get User Details
	$aProfile = _kickapps_get_profile($iUserId);

	$sFirstName = ucwords($aProfile["profile_first_name"]);
	$sLastName = ucwords($aProfile["profile_last_name"]);
	# --END Get User Details

	# Jose Magsaysay Elementary School old username format
	$sOldUserName = "H_".strtolower((substr($sFirstName, 0, 1)).$sLastName)."-jmes";

	$oKAClient = new SOAPClient("http://affiliate.kickapps.com/kickapps/soap/KaSoapSvc?WSDL");
	$oKAClient->trace = 4;

	$oDoc = new DomDocument('1.0', 'UTF-8');

	$aHeaderInput = array('ns2:AffiliateUserName' => $sAffUserName, 'ns2:AffiliateUserEmail' =>$sAffUserEmail);
	$oHeaderVar = new SoapVar($aHeaderInput, SOAP_ENC_OBJECT);
	$oHeadErt = new SoapHeader('http://schemas.kickapps.com/services/soap',	'AffiliateAuthenticationToken', $oHeaderVar);
	$oKAClient->__setSoapHeaders(array($oHeadErt));

	$nodeKassoRequest = $oDoc->createElementNS("http://schemas.kickapps.com/services/soap","KassoRequest");
	$nodeKassoRequest = $oDoc->appendChild($nodeKassoRequest);
	$requestName = $nodeKassoRequest->setAttribute("requestName", $sRequestType);

	$nodeaffiliateUserName = $oDoc->createElement("Param");
	$newnodeaffiliateUserName = $nodeKassoRequest->appendChild($nodeaffiliateUserName);
	$paraNameAttr = $nodeaffiliateUserName->setAttribute("paramName", "affiliateUserName");
	$paramValue = $nodeaffiliateUserName->setAttribute("paramValue", $sAffUserName);

	$nodeaffiliateEmail = $oDoc->createElement("Param");
	$newnodeaffiliateEmail = $nodeKassoRequest->appendChild($nodeaffiliateEmail);
	$paraNameAttr = $nodeaffiliateEmail->setAttribute("paramName", "affiliateEmail");
	$paramValue = $nodeaffiliateEmail->setAttribute("paramValue", $sAffUserEmail);

	$nodeaffiliateSiteName = $oDoc->createElement("Param");
	$newnodeaffiliateSiteName = $nodeKassoRequest->appendChild($nodeaffiliateSiteName);
	$paraNameAttr = $nodeaffiliateSiteName->setAttribute("paramName", "affiliateSiteName");
	$paramValue = $nodeaffiliateSiteName->setAttribute("paramValue", $sAffSiteName);

	$nodeuserName = $oDoc->createElement("Param");
	$newnodeuserName = $nodeKassoRequest->appendChild($nodeuserName);
	$paraNameAttr = $nodeuserName->setAttribute("paramName", "userName");
	$paramValue = $nodeuserName->setAttribute("paramValue", $sOldUserName);

	$nodeoldUserName = $oDoc->createElement("Param");
	$newnodeoldUserName = $nodeKassoRequest->appendChild($nodeoldUserName);
	$paraNameAttr = $nodeoldUserName->setAttribute("paramName", "newUserName");
	$paramValue = $nodeoldUserName->setAttribute("paramValue", $sUserName);

	$nodeemail = $oDoc->createElement("Param");
	$newnodeemail = $nodeKassoRequest->appendChild($nodeemail);
	$paraNameAttr = $nodeemail->setAttribute("paramName", "email");
	$paramValue = $nodeemail->setAttribute("paramValue", $sEmail);

	$oDoc->appendChild($nodeKassoRequest);

	try{
		$sResult = $oKAClient->processRequest($oDoc->saveXML());
		//dump_this($sResult);
	}catch(SOAPFault $oSoapEx){
		//dump_this($oSoapEx->getMessage());
		watchdog("KickApps Error", $oSoapEx->getMessage()." Email: ".$sEmail.". User: ".$sUserName.".");
	} */

	_kickapps_sign_in($oUser, 1);
	//Kickapps_testjedjed($oUser, 1);
}

function Kickapps_testjedjed($oUser, $test){

	$iUserId = $oUser->uid;

	$sAffUserName = variable_get('kickapps_username', '');
	$sAffUserEmail = variable_get('kickapps_email', '');
	$sAffSiteName = variable_get('kickapps_sitename', '');
	$sRequestType = "signInRegisterUser";

	$sUserName = $oUser->name;
	$sEmail = $oUser->mail;

	# --BEGIN Get User Details
	$aProfile = _kickapps_get_profile($iUserId);

	$sFirstName = ucwords($aProfile["profile_first_name"]);
	$sLastName = ucwords($aProfile["profile_last_name"]);
	# --END Get User Details

	$oKAClient = new SOAPClient("http://affiliate.kickapps.com/kickapps/soap/KaSoapSvc?WSDL");
	$oKAClient->trace = 4;

	$oDoc = new DomDocument('1.0', 'UTF-8');

	$aHeaderInput = array('ns2:AffiliateUserName' => $sAffUserName, 'ns2:AffiliateUserEmail' =>$sAffUserEmail);
	$oHeaderVar = new SoapVar($aHeaderInput, SOAP_ENC_OBJECT);
	$oHeadErt = new SoapHeader('http://schemas.kickapps.com/services/soap',	'AffiliateAuthenticationToken', $oHeaderVar);
	$oKAClient->__setSoapHeaders(array($oHeadErt));

	$nodeKassoRequest = $oDoc->createElementNS("http://schemas.kickapps.com/services/soap","KassoRequest");
	$nodeKassoRequest = $oDoc->appendChild($nodeKassoRequest);
	$requestName = $nodeKassoRequest->setAttribute("requestName", 'signInRegisterUser');

	$nodeaffiliateUserName = $oDoc->createElement("Param");
	$newnodeaffiliateUserName = $nodeKassoRequest->appendChild($nodeaffiliateUserName);
	$paraNameAttr = $nodeaffiliateUserName->setAttribute("paramName", "affiliateUserName");
	$paramValue = $nodeaffiliateUserName->setAttribute("paramValue", $sAffUserName);

	$nodeaffiliateEmail = $oDoc->createElement("Param");
	$newnodeaffiliateEmail = $nodeKassoRequest->appendChild($nodeaffiliateEmail);
	$paraNameAttr = $nodeaffiliateEmail->setAttribute("paramName", "affiliateEmail");
	$paramValue = $nodeaffiliateEmail->setAttribute("paramValue", $sAffUserEmail);

	$nodeaffiliateSiteName = $oDoc->createElement("Param");
	$newnodeaffiliateSiteName = $nodeKassoRequest->appendChild($nodeaffiliateSiteName);
	$paraNameAttr = $nodeaffiliateSiteName->setAttribute("paramName", "affiliateSiteName");
	$paramValue = $nodeaffiliateSiteName->setAttribute("paramValue", $sAffSiteName);

	$nodeuserName = $oDoc->createElement("Param");
	$newnodeuserName = $nodeKassoRequest->appendChild($nodeuserName);
	$paraNameAttr = $nodeuserName->setAttribute("paramName", "userName");
	$paramValue = $nodeuserName->setAttribute("paramValue", $sUserName);

	/*$nodeoldUserName = $oDoc->createElement("Param");
	$newnodeoldUserName = $nodeKassoRequest->appendChild($nodeoldUserName);
	$paraNameAttr = $nodeoldUserName->setAttribute("paramName", "newUserName");
	$paramValue = $nodeoldUserName->setAttribute("paramValue", $newusname);*/

	$nodeemail = $oDoc->createElement("Param");
	$newnodeemail = $nodeKassoRequest->appendChild($nodeemail);
	$paraNameAttr = $nodeemail->setAttribute("paramName", "email");
	$paramValue = $nodeemail->setAttribute("paramValue", $sEmail);

	$oDoc->appendChild($nodeKassoRequest);

	try{
		$sResult = $oKAClient->processRequest($oDoc->saveXML());
		//dump_this($sResult);
	}catch(SOAPFault $oSoapEx){
		//dump_this($oSoapEx->getMessage());
		watchdog("KickApps Error", $oSoapEx->getMessage()." Email: ".$sEmail.". User: ".$sUserName.". Affsitename: ".$sAffSiteName.". sAffUserEmail: ".$sAffUserEmail.". sAffUserName: ".$sAffUserName.".");
	}

	return true;
}


function kickapps_user($op, &$edit, &$account, $category = NULL) {

  $kid = kickapps_getStatus();

  if($kid == 1){
	switch ($op){
		case ("login"):
			$aRoles = $account->roles;

			//var_dump($aRoles);
			//if (array_key_exists(9, $aRoles)) _kickapps_update_user($account);

			_kickapps_update_user($account);
			break;
		case ("insert"):
			_kickapps_sign_in($account, 0);
			break;
	}
 }
}

function kickapps_filter($op, $delta = 0, $format = -1, $text = '') {
	// The "list" operation provides the module an opportunity to declare both how
	// many filters it defines and a human-readable name for each filter. Note that
	// the returned name should be passed through t() for translation.
	if ($op == 'list') return array(0 => t('Append Session ID and Transaction ID for KickApps'));

	watchdog("KickApps", "In filter");

	// All operations besides "list" provide a $delta argument so we know which
	// filter they refer to. We'll switch on that argument now so that we can
	// discuss each filter in turn.
	switch($delta){
		// First we define the simple string substitution filter.
		case 0:
			switch($op){
				// This description is shown in the administrative interface, unlike the
				// filter tips which are shown in the content editing interface.
				case 'description':
					return t('Appends any KickApps widgets with the logged in users information');

				case 'no cache':
					return true;

				// We don't need the "prepare" operation for this filter, but it's required
				// to at least return the input text as-is.
				case 'prepare':
					return $text;

				// The actual filtering is performed here. The supplied text should be
				// returned, once any necessary substitutions have taken place.
				case 'process':
					$ka_st = $_SESSION['ka_st'];
					$ka_tid = $_SESSION['ka_tid'];

					if ($ka_st != '' && $ka_st != null) {
						$text = str_replace('.kickAction?', '.kickAction?st=' .$ka_st . '&tid=' .$ka_tid . '&' , $text);
						$text = str_replace('<param name="FlashVars" value="', '<param name="FlashVars" value="st=' .$ka_st . '&amp;tid=' .$ka_tid . '&amp;' , $text);
						$text = str_replace('<Param name="FlashVars" value="', '<Param name="FlashVars" value="st=' .$ka_st . '&amp;tid=' .$ka_tid . '&amp;' , $text);
						$text = str_replace('FlashVars="', 'FlashVars="st=' .$ka_st . '&amp;tid=' .$ka_tid . '&amp;' , $text);
					}

					return $text;
			}

			break;
	}
}

function _kickapps_get_profile($iUserId){
	$sqlProfile = "SELECT B.uid, A.name, B.value
					FROM {profile_fields} A INNER JOIN {profile_values} B ON A.fid = B.fid
					WHERE B.uid = %d";

	$oQueryResult = db_query($sqlProfile, $iUserId);
	$aDetails = array();

	while ($oDetails = db_fetch_object($oQueryResult)){
		$aDetails[$oDetails->name] = $oDetails->value;
	}
	mysqli_free_result($oQueryResult);

	return $aDetails;
}

function Kickapps_update_username($newusname, $oldusname, $user){

	$oUser = $user;
	$iUserId = $oUser->uid;

	$sAffUserName = variable_get('kickapps_username', '');
	$sAffUserEmail = variable_get('kickapps_email', '');
	$sAffSiteName = variable_get('kickapps_sitename', '');
	$sRequestType = "changeUserName";

	$sUserName = $oUser->name;
	$sEmail = $oUser->mail;

	# --BEGIN Get User Details
	$aProfile = _kickapps_get_profile($iUserId);

	$sFirstName = ucwords($aProfile["profile_first_name"]);
	$sLastName = ucwords($aProfile["profile_last_name"]);
	# --END Get User Details

	$oKAClient = new SOAPClient("http://affiliate.kickapps.com/kickapps/soap/KaSoapSvc?WSDL");
	$oKAClient->trace = 4;

	$oDoc = new DomDocument('1.0', 'UTF-8');

	$aHeaderInput = array('ns2:AffiliateUserName' => $sAffUserName, 'ns2:AffiliateUserEmail' =>$sAffUserEmail);
	$oHeaderVar = new SoapVar($aHeaderInput, SOAP_ENC_OBJECT);
	$oHeadErt = new SoapHeader('http://schemas.kickapps.com/services/soap',	'AffiliateAuthenticationToken', $oHeaderVar);
	$oKAClient->__setSoapHeaders(array($oHeadErt));

	$nodeKassoRequest = $oDoc->createElementNS("http://schemas.kickapps.com/services/soap","KassoRequest");
	$nodeKassoRequest = $oDoc->appendChild($nodeKassoRequest);
	$requestName = $nodeKassoRequest->setAttribute("requestName", 'changeUserName');

	$nodeaffiliateUserName = $oDoc->createElement("Param");
	$newnodeaffiliateUserName = $nodeKassoRequest->appendChild($nodeaffiliateUserName);
	$paraNameAttr = $nodeaffiliateUserName->setAttribute("paramName", "affiliateUserName");
	$paramValue = $nodeaffiliateUserName->setAttribute("paramValue", $sAffUserName);

	$nodeaffiliateEmail = $oDoc->createElement("Param");
	$newnodeaffiliateEmail = $nodeKassoRequest->appendChild($nodeaffiliateEmail);
	$paraNameAttr = $nodeaffiliateEmail->setAttribute("paramName", "affiliateEmail");
	$paramValue = $nodeaffiliateEmail->setAttribute("paramValue", $sAffUserEmail);

	$nodeaffiliateSiteName = $oDoc->createElement("Param");
	$newnodeaffiliateSiteName = $nodeKassoRequest->appendChild($nodeaffiliateSiteName);
	$paraNameAttr = $nodeaffiliateSiteName->setAttribute("paramName", "affiliateSiteName");
	$paramValue = $nodeaffiliateSiteName->setAttribute("paramValue", $sAffSiteName);

	$nodeuserName = $oDoc->createElement("Param");
	$newnodeuserName = $nodeKassoRequest->appendChild($nodeuserName);
	$paraNameAttr = $nodeuserName->setAttribute("paramName", "userName");
	$paramValue = $nodeuserName->setAttribute("paramValue", $oldusname);

	$nodeoldUserName = $oDoc->createElement("Param");
	$newnodeoldUserName = $nodeKassoRequest->appendChild($nodeoldUserName);
	$paraNameAttr = $nodeoldUserName->setAttribute("paramName", "newUserName");
	$paramValue = $nodeoldUserName->setAttribute("paramValue", $newusname);

	$nodeemail = $oDoc->createElement("Param");
	$newnodeemail = $nodeKassoRequest->appendChild($nodeemail);
	$paraNameAttr = $nodeemail->setAttribute("paramName", "email");
	$paramValue = $nodeemail->setAttribute("paramValue", $sEmail);

	$oDoc->appendChild($nodeKassoRequest);

	try{
		$sResult = $oKAClient->processRequest($oDoc->saveXML());
		//dump_this($sResult);
	}catch(SOAPFault $oSoapEx){
		//dump_this($oSoapEx->getMessage());
		watchdog("KickApps Error", $oSoapEx->getMessage()." Email: ".$sEmail.". User: ".$sUserName.".");
	}

	return true;
}
?>
