var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Sun",
            "mon": "Mon",
            "tue": "Tue",
            "wed": "Wed",
            "thu": "Thu",
            "fri": "Fri",
            "sat": "Sat",
            "jan": "Jan",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Apr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Aug",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dec"
        },
        "no_implemented": "Not implemented yet",
        "to_date_view": "Click to view the current date",
        "i_undefined": "Undefined",
        "allday_event": "All day duty",
        "repeat_event": "Repeat duty",
        "time": "Time",
        "event": "Duty",
        "location": "Location",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "New duty",
        "confirm_delete_event": "Do you confirm to delete this duty? ",
        "confrim_delete_event_or_all": "Do you want to all repeat duties or only this duty? \r\nClick [OK] to delete only this duty, click [Cancel] delete all duties",
        "data_format_error": "Data format error! ",
        "invalid_title": "Duty title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "e.g., please come to the cybrary asap.",
        "content": "What",
        "create_event": "Create duty",
        "update_detail": "Edit details",
        "click_to_detail": "View details",
        "i_delete": "Delete",
        "day_plural": "days",
        "others": "Others",
        "item": ""
    }
});
